### PR TITLE
Fix saving of number preferences

### LINKED ISSUE #3151: preference is not saving [2021.1.0]
**Describe the bug**
my preference is not saving after using portable(was using previous installed version).
max history and chunk size using null values all the time and not saving histories.

I have tried to delete all local/roam data 3 times for installed version and portable version.
now using older version 2020.5.5.2, which is working fine

### PR DESCRIPTION
**Pull request by develohpanda**
What it says on the tin.

Closes #3151

### CODE REVIEW

File: packages/insomnia-app/app/ui/components/settings/general.js [hunk 1]
```diff
@@ -90,8 +90,8 @@ class General extends React.PureComponent<Props, State> {
       const min = parseInt(el.min, 10);
       const max = parseInt(el.max, 10);
 
-      const moreThanMax = Number.isNaN(max) || value > max;
-      const lessThanMin = Number.isNaN(min) || value < min;
+      const moreThanMax = !Number.isNaN(max) && value > max;
+      const lessThanMin = !Number.isNaN(min) && value < min;
```
Comment (develohpanda) [inline packages/insomnia-app/app/ui/components/settings/general.js]: These conditions were slightly adjusted during the last part of the PR which introduced it; unfortunately the negation was not updated correctly, but this is now resolved.

**Review by DMarby — APPROVED** [review]

**Review by sonicyeti — APPROVED** [review]
Nice
