### PR TITLE
fix: URL PREVIEW cut off first few lines for very long URL [INS-3640]

### LINKED ISSUE #7178: URL PREVIEW cut off first few lines for very long URL
### Expected Behavior

This happens for very long URL (e.g. a URL with jwt token)

With scrollbar, I should be able to scroll all the way to top / first display line of URL (after wrap)
See screenshot
image

### Actual Behavior

For a very long URL, e.g. a URL with JWT, the display is cut off (when it is more than 6 lines)

### Reproduction Steps

When I narrow down the size of URL preview. The first display line is gone. The scrollbar failed to scroll all the way up to the top. As the screenshot shows, I can not see the first display line of the URL:

Begin to cut the first line:
image

the first two lines are completely gone
image

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

For any URL more than 6 lines of display after wrap. The issue happens. 

### Insomnia Version

8.6.1

### What operating system are you using?

macOS

### Operating System Version

sonoma 14.3.1

### Installation method

Download from https://insomnia.rest/download

### Last Known Working Insomnia version

_No response_

### PR DESCRIPTION
**Pull request by CurryYangxx**
Closes #7178 

Change

- delete the wrapper alignItems style
- use margin auto to keep vertical center

How to test
- Enter a long URL. When it exceeds the maximum height of the URL preview box, it can slide normally to top.

### CODE REVIEW

**Review by ihexxa — APPROVED** [review]

File: packages/insomnia/src/ui/components/rendered-query-string.tsx [hunk 1]
```diff
@@ -82,7 +82,7 @@ export const RenderedQueryString: FC<Props> = ({ request }) => {
 
   return (
     <Wrapper>
-      <span className={className}>{previewString}</span>
+      <span className={classNames('my-auto', className)}>{previewString}</span>
```
Comment (marckong) [inline packages/insomnia/src/ui/components/rendered-query-string.tsx:85]: nit:

Is there a reason for using my-auto as the class name?

**Review by marckong — APPROVED** [review]
LGTM. I may suggest if we add screenshot, it would help reviewers who haven't touched the codebase for a while (:p) to understand the changes

File: packages/insomnia/src/ui/components/rendered-query-string.tsx (hunk 1 above)
Comment (ihexxa) [reply packages/insomnia/src/ui/components/rendered-query-string.tsx:85]: It should be from tailwind.

Comment (marckong) [reply packages/insomnia/src/ui/components/rendered-query-string.tsx:85]: thanks!

**Comment by CurryYangxx** [comment]
> LGTM. I may suggest if we add screenshot, it would help reviewers who haven't touched the codebase for a while (:p) to understand the changes

Good idea, I will add screenshots in future PRs
