### PR TITLE
Handle empty security object in openapi3

### LINKED ISSUE #2167: Openapi3 spec with empty item in security schema fails to import
**Describe the bug**
I can't import a Json OpenApi file.

**To Reproduce**
Hello,

I have an OpenApi Json file that generate an error when I try to import it in Insomnia Designer.
This file can be opened in Swgger Editor and this editor does not report any problem.
Here is the error message I have when I try to import the json file :
`
Import Failed
TypeError:
result.summary[_models_WEBPACK_IMPORTED_MODULE_11__.workspace.type]

Import failed
Cannot read property 'type' of undefined
`

For confidentiality reasons I cannot publish this JSON file here but I can send it to you by email.
**Expected behavior**
The file should be imported.

**Desktop (please complete the following information):**
 - Windows 10 Professional Version 10.0.18363 Number 18363
 - Installation via your website
 - App Version [e.g. v7.0.3]

### PR DESCRIPTION
**Pull request by develohpanda**
Closes #2167, to handle the case where a security object under a path contains an empty item.

Also updates the import to show an error dialog _before_ trying to extract workspaces, if there is a failure during import. This should give more informative error messages.

image

### CODE REVIEW

File: packages/insomnia-app/app/ui/redux/modules/global.js [hunk 1]
```diff
@@ -277,15 +279,19 @@ export function importFile(workspaceId: string, forceToWorkspace?: ForceToWorksp
...
           const result = await importUtils.importUri(
             askToImportIntoWorkspace(workspaceId, forceToWorkspace),
             uri,
           );
-          importedWorkspaces = [...importedWorkspaces, ...result.summary[models.workspace.type]];
+          const workspaces = handleImportResult(
+            result,
+            'The file does not contain a valid specification.',
+          );
+          importedWorkspaces.push(workspaces);
```
Comment (gschier) [inline packages/insomnia-app/app/ui/redux/modules/global.js]: Shouldn't this be `importedWorkspaces.push(...workspaces)`?

**Review by gschier — CHANGES_REQUESTED** [review]
Looks good! Just a minor comment

File: packages/insomnia-app/app/ui/redux/modules/global.js (hunk 1 above)
Comment (develohpanda) [reply packages/insomnia-app/app/ui/redux/modules/global.js]: Simplified - `importedWorkspaces` is always initialized to `[]`, so we can simply reassign the variable rather than having to operate on the array. 👍 

But yep, using `.push` would require the spread operator. My bad!

**Review by gschier — APPROVED** [review]
