### PR TITLE
Editor toggling, visual design spec. integration, various stylistic tweaks

### LINKED ISSUE #2562: Unit Testing > UI Lag
**Describe the bug**
When multiple test suites exist, each containing multiple tests the Unit Testing UI is slow to initially render.

**To Reproduce**
See replication steps [here](https://github.com/Kong/insomnia/issues/2562#issuecomment-681013144).

**Expected behavior**
Near zero lag.

**Desktop (please complete the following information):**
image

### PR DESCRIPTION
**Pull request by sonicyeti**
This PR covers the incorporation of accordion style functionality for unit tests including: 

- Unit tests can now be toggled to expand or collapse
- A single unit test's max height caps at around the 20 line mark, where scrolling takes over to preserve real estate
- The unit test header has been brought closer to alignment with the original design specification
- Unit Test is now a list group item type from a component standpoint
- Swapping play and delete iconography positioning
- Resolution for multiple Code Mirror instances introducing lag

**Screenshot:**
Screen Shot 2020-09-10 at 10 00 43 AM

**Demo:**

Closes #2562
Fixes INS-85
Fixes INS-48
Fixes INS-52

### CODE REVIEW

**Review by DMarby — APPROVED** [review]

File: packages/insomnia-app/app/ui/components/unit-test-selection.js [hunk 1]
```diff
@@ -0,0 +1,29 @@
+// @flow
+import React from 'react';
+
+type Props = {
+  onChange: Function,
+  unitTest: Object,
+  selectableRequests: Object,
```
Comment (develohpanda) [inline packages/insomnia-app/app/ui/components/unit-test-selection.js]: It would be great if we could type these more explicitly.

For example, just from looking at the usage in the component
```suggestion
  onChange: () => void,
  selectedRequestId?: string,
  selectableRequests: Array<{name: string, request: { _id: string }}>,
```

File: packages/insomnia-app/app/ui/components/unit-test-selection.js [hunk 2]
```diff
@@ -0,0 +1,29 @@
...
+};
+
+export default function UnitTestSelection({ onChange, unitTest, selectableRequests }: Props) {
```
Comment (develohpanda) [inline packages/insomnia-app/app/ui/components/unit-test-selection.js]: Suggestion to rename component as `UnitTestRequestSelector`, as this is specific to selecting requests 😄

File: packages/insomnia-app/app/ui/components/wrapper-unit-test.js [hunk 3]
```diff
@@ -351,45 +352,28 @@ class WrapperUnitTest extends React.PureComponent<Props, State> {
...
+      <UnitTestItem
+        item={unitTest}
+        key={unitTest._id}
+        testSelection={
+          <UnitTestSelection
+            onChange={this._handleSetActiveRequest.bind(this, unitTest)}
+            unitTest={unitTest}
+            selectableRequests={selectableRequests}
+          />
+        }
```
Comment (develohpanda) [inline packages/insomnia-app/app/ui/components/wrapper-unit-test.js]: I like that you extracted `UnitTestItem` and `UnitTestSelection` out into standalone components 👍 

We can avoid having to pass `<UnitTestSelection />` as a prop into `UnitTestItem`; instead, we can simply pass the onChange handler as a prop, for instance, `onRequestSelectionChanged={this._handleSetActiveRequest.bind(this, unitTest)}`.

Then, `UnitTestItem` becomes

```js
function UnitTestItem(props) {
  ...
  <UnitTestSelection onChange={props.onRequestSelectionChanged} ... />
  ...
}
```
instead of
```js
function UnitTestItem(props) {
  ...
  {props.testSelection}
  ...
}
```

This way UnitTestSelection can be moved into insomnia-components!

File: packages/insomnia-app/app/ui/components/wrapper-unit-test.js [hunk 4]
```diff
@@ -351,45 +352,28 @@ class WrapperUnitTest extends React.PureComponent<Props, State> {
...
+        onDeleteTest={() => this._handleDeleteTest(unitTest)}
+        onRunTest={() => this._handleRunTest(unitTest)}
```
Comment (develohpanda) [inline packages/insomnia-app/app/ui/components/wrapper-unit-test.js]: Passing arrow functions as props mean a new function is instantiated on each render. A newly instantiated function, even if it has the same implementation, is unique. Because it is unique, React will tell `UnitTestItem` to update, because a prop has changed, when in-fact it hasn't. Try use the `.bind` syntax within class components, or `React.useCallback` within function components 😄

File: packages/insomnia-components/components/list-group/list-group.stories.js [hunk 5]
```diff
@@ -47,10 +48,47 @@ const tests = [
...
+    code:
+      'const response1 = await insomnia.send();\nexpect(response1.status).to.equal(404);\nconst response1 = await insomnia.send();\nexpect(response1.status).to.equal(404);\nconst response1 = await insomnia.send();\nexpect(response1.status).to.equal(404);\nconst response1 = await insomnia.send();\nexpect(response1.status).to.equal(404);\nconst response1 = await insomnia.send();\nexpect(response1.status).to.equal(404);',
+  },
+];
+
+export const _unitTests = () => (
+  <div style={{ width: '100%' }}>
+    <ListGroup>
+      {unitTests.map((test, i) => (
+        <UnitTestItem item={test} key={i}>
```
Comment (develohpanda) [inline packages/insomnia-components/components/list-group/list-group.stories.js]: Index as keys hehe. Doesn't really matter here, but good to get into the practice of avoiding it. I suggest to use `test._id` as the key

File: packages/insomnia-app/app/ui/components/wrapper-unit-test.js [hunk 6]
```diff
@@ -351,45 +352,28 @@ class WrapperUnitTest extends React.PureComponent<Props, State> {
...
+        testsRunning={testsRunning}
+        testNameEditable={
+          <UnitTestEditable
+            onSubmit={this._handleChangeTestName.bind(this, unitTest)}
+            value={unitTest.name}
+          />
+        }>
```
Comment (develohpanda) [inline packages/insomnia-app/app/ui/components/wrapper-unit-test.js:371]: Same as above, but less trivial because `Editable` isn't in `insomnia-components`. _But_, it would be a great idea to pull `Editable` into the component library, and other usages can be updated later on.

File: packages/insomnia-components/components/list-group/unit-test-item.js [hunk 7]
```diff
@@ -0,0 +1,108 @@
...
+const UnitTestItem = ({
+  item,
+  children,
+  onDeleteTest,
+  onRunTest,
+  testSelection,
+  testNameEditable,
+  testsRunning,
+}: Props) => {
+  const [collapse, toggleCollapse] = React.useState(false);
```
Comment (develohpanda) [inline packages/insomnia-components/components/list-group/unit-test-item.js]: We can use the `useToggle` hook from `react-use`, like in the new sidebar hehe

File: packages/insomnia-components/components/list-group/unit-test-item.js [hunk 8]
```diff
@@ -0,0 +1,108 @@
...
+      <div>
+        <Button
+          onClick={() => toggleCollapse(!collapse)}
+          variant="text"
+          style={!collapse ? { transform: `rotate(${toggleRotation}deg)` } : {}}>
+          <SvgIcon icon="chevron-down" />
+        </Button>
+        <Button variant="text" disabled>
+          <SvgIcon icon="file" />
+        </Button>
```
Comment (develohpanda) [inline packages/insomnia-components/components/list-group/unit-test-item.js:79]: Does this icon need to exist inside a disabled `Button`? I'm guessing it's for consistent spacing

**Review by develohpanda — CHANGES_REQUESTED** [review]
Nicely done 😄 

I've made a couple of comments, but one overarching one is to do with defining Props for components. Because props are the interface between a component and it's consumer, we should try to be as explicit as possible with the prop type definitions, rather than generic `Function`, `Object`, etc. It will only help us when we come to look at or consume the same component in a few months time.

I will add that there are many components currently that do not define their prop types clearly; those components were likely created before a typing methodology was introduced. Even though we are currently using Flow right now, when we eventually look to move towards TS, the flow type definitions will be useful. 😄

File: packages/insomnia-components/components/list-group/unit-test-item.js (hunk 8 above)
Comment (sonicyeti) [reply packages/insomnia-components/components/list-group/unit-test-item.js:79]: Exactly. Disabled happened to match the design spec while reducing custom styling overhead.

File: packages/insomnia-app/app/ui/components/wrapper-unit-test.js [hunk 9]
```diff
@@ -354,20 +353,18 @@ class WrapperUnitTest extends React.PureComponent<Props, State> {
     const { testsRunning } = this.state;
     const selectableRequests = this.buildSelectableRequests();
 
+    console.log(selectableRequests);
```
Comment (DMarby) [inline packages/insomnia-app/app/ui/components/wrapper-unit-test.js]: I think this might be a leftover debug statement that should be removed?

Comment (sonicyeti) [reply packages/insomnia-app/app/ui/components/wrapper-unit-test.js]: Thanks for the catch, pulling it now!

File: packages/insomnia-components/components/list-group/list-group.stories.js [hunk 10]
```diff
@@ -73,12 +77,119 @@ const unitTests = [
...
-        <UnitTestItem item={test} key={i}>
-          <div>Toggle Content...</div>
+        <UnitTestItem
+          testNameEditable={test.name}
+          item={test}
+          key={test._id}
+          onChange={_handleRequestSelected}
+          selectableRequests={unitTestRequests}>
+          <div style={{ padding: '10px 15px', border: '1px solid #eee', margin: '10px' }}>
+            CodeMirror instance.
```
Comment (develohpanda) [inline packages/insomnia-components/components/list-group/list-group.stories.js:191]: 👌

File: packages/insomnia-components/components/list-group/list-group.stories.js [hunk 11]
```diff
@@ -89,7 +200,7 @@ export const _unitTestResults = () => (
   <div style={{ width: '350px' }}>
     <ListGroup>
       {unitTestResults.map((test, i) => (
-        <UnitTestResultItem item={test} key={i} />
+        <UnitTestResultItem item={test} key={test._id} />
```
Comment (develohpanda) [inline packages/insomnia-components/components/list-group/list-group.stories.js:203]: 👌

File: packages/insomnia-components/components/list-group/unit-test-item.js [hunk 12]
```diff
@@ -63,27 +49,36 @@ const UnitTestItem = ({
...
+  selectedRequestId,
+  selectableRequests,
 }: Props) => {
-  const [collapse, toggleCollapse] = React.useState(false);
-  const toggleRotation = -90;
+  const [isToggled, toggle] = useToggle(false);
+  const toggleIconRotation = -90;
+  const _handleItemToggle = React.useCallback(() => {
+    toggle();
+  }, [toggle]);
```
Comment (develohpanda) [inline packages/insomnia-components/components/list-group/unit-test-item.js]: I think this can be removed in favor of just using `onClick={toggle}`

The `React.useCallback` would be useful if you were to do `onClick={() => { toggle() }}`, because the `() => {}` syntax creates a new function. 🙂

File: packages/insomnia-components/components/list-group/unit-test-item.js [hunk 13]
```diff
@@ -1,41 +1,27 @@
...
   item: Object,
   children?: React.Node,
-  onDeleteTest?: Function,
-  onRunTest?: Function,
-  testSelection?: React.Node,
+  onDeleteTest?: () => void,
+  onRunTest?: () => void,
   testNameEditable?: React.Node,
   testsRunning?: Object,
+  onChange: () => void,
```
Comment (develohpanda) [inline packages/insomnia-components/components/list-group/unit-test-item.js]: It's not immediately clear what this change handler is for - changing the test body, title, request, etc?

Similar to the other event handles (`onDeleteTest`, `onRunTest`), I suggest naming this explicitly like `onSetActiveRequest`, for example.

`onChange` on it's own is fine for a generic component like `Editable`, though. Contextual 😄

File: packages/insomnia-components/components/list-group/unit-test-item.js [hunk 14]
```diff
@@ -1,41 +1,27 @@
...
+import UnitTestRequestSelector from './unit-test-request-selector';
 
 type Props = {|
   item: Object,
   children?: React.Node,
-  onDeleteTest?: Function,
-  onRunTest?: Function,
-  testSelection?: React.Node,
+  onDeleteTest?: () => void,
+  onRunTest?: () => void,
```
Comment (develohpanda) [inline packages/insomnia-components/components/list-group/unit-test-item.js:15]: I'd like to double check but I don't think these callbacks should be optional, right?

File: packages/insomnia-components/components/list-group/unit-test-item.js [hunk 15]
```diff
@@ -1,41 +1,27 @@
...
   testsRunning?: Object,
+  onChange: () => void,
+  selectedRequestId?: string,
+  selectableRequests: Array<{ name: string, request: { _id: string } }>,
 |};
 
 const StyledResultListItem: React.ComponentType<{}> = styled(ListGroupItem)`
   padding: 0 var(--padding-sm);
 
-  .form-control {
```
Comment (develohpanda) [inline packages/insomnia-components/components/list-group/unit-test-item.js]: Yay, happy to see this move into what uses it specifically. 😄

File: packages/insomnia-components/components/list-group/unit-test-item.js [hunk 16]
```diff
@@ -94,13 +89,7 @@ const UnitTestItem = ({
           <SvgIcon icon="play" />
         </Button>
       </div>
-      {collapse && (
-        <div
-          initial={{ height: collapse ? '100%' : '0px' }}
-          animate={{ height: collapse ? '100%' : '0px' }}>
```
Comment (develohpanda) [inline packages/insomnia-components/components/list-group/unit-test-item.js]: Was the removal of animation intentional?

File: packages/insomnia-components/index.js [hunk 17]
```diff
@@ -33,6 +34,7 @@ export const ListGroup = _ListGroup;
 export const ListGroupItem = _ListGroupItem;
 export const UnitTestItem = _UnitTestItem;
 export const UnitTestResultItem = _UnitTestResultItem;
+export const UnitTestRequestSelector = _UnitTestRequestSelector;
```
Comment (develohpanda) [inline packages/insomnia-components/index.js]: We can get away with not exporting this selector from insomnia-components since it's more of an internal component. Keen for your thoughts on this however - what stuff is exported from the library and what is not.

**Review by develohpanda — APPROVED** [review]
A couple of minor notes, good to merge after they are addressed. 👍

File: packages/insomnia-components/index.js (hunk 17 above)
Comment (sonicyeti) [reply packages/insomnia-components/index.js]: 100% agreed, I didn't realize that this export serves the sole purpose of exposing it for usage in app. I thought it was necessary for bundling deps which the UT result item needs. I'll yank it!

File: packages/insomnia-components/components/list-group/unit-test-item.js (hunk 16 above)
Comment (sonicyeti) [reply packages/insomnia-components/components/list-group/unit-test-item.js]: ~~I pulled this because while we can slide-reveal the CM instance, when collapsed, it no longer exists in the DOM and looks quite janky when attempting to slide-hide and wanted to avoid having a toggle collapsed callback tied to the tween duration just for the sake of animating the exit of the CM instance.~~

Decided to keep and enable it. It just looks so much better sliding into view despite it immediately disappearing on collapse.

Comment (develohpanda) [reply packages/insomnia-components/components/list-group/unit-test-item.js]: Fair enough, we can alter it depending on feedback. Either way seems fine
