### PR TITLE
fix: prevent app restart when editor setting change [INS-3668]

### LINKED ISSUE #6389: On Macbook, the shortcut to launch environment variables caused insomnia crashed
### Expected Behavior

On Macbook, you either use the default keyboard shortcut and any customized shortcut to launch the environment variable selection, the insomnia gets crashed immediately. 

### Actual Behavior

the environment variable selection should be launched by keyboard shortcut

### Reproduction Steps

_No response_

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

_No response_
image

### Insomnia Version

Version: Insomnia 2023.4.0

### What operating system are you using?

macOS

### Operating System Version

macos 12.3

### Installation method

homebrew

### Last Known Working Insomnia version

_No response_

### PR DESCRIPTION
**Pull request by CurryYangxx**
Close #6389 

There is a historical logic when `nunjucksPowerUserMode` and `showVariableSourceAndValue` change the app will restart，in order to modify how variables are displayed
https://github.com/Kong/insomnia/blob/6c63b0d8d3a8b37c813a8c2fc0584e2d20f7e166/packages/insomnia/src/ui/hooks/use-settings-side-effects.ts#L58

The purpose of this PR is to use other way to refresh editor

Changes:

- [x] add a hook to listen showVariableSourceAndValue and nunjucksPowerUserMode variable change 
    - [x] one-line editor
    - [x] code editor
- [x] extract the init and clean up logic to external  function 
- [x] run cleanup and init to reinitialize codeMirror editor
- [x] delete old app restart logic

### CODE REVIEW

File: packages/insomnia/src/ui/components/settings/general.tsx [hunk 1]
```diff
@@ -27,14 +26,14 @@ import { TextSetting } from './text-setting';
...
-  </Fragment>
-);
+// const RestartTooltip: FC<{ message: string }> = ({ message }) => (
+//   <Fragment>
+//     {message}{' '}
+//     <Tooltip message="Will restart the app" className="space-left">
+//       <i className="fa fa-refresh super-duper-faint" />
+//     </Tooltip>
+//   </Fragment>
+// );
```
Comment (jackkav) [inline packages/insomnia/src/ui/components/settings/general.tsx]:
```suggestion
```

File: packages/insomnia/src/ui/components/settings/general.tsx [hunk 2]
```diff
@@ -27,14 +26,14 @@ import { TextSetting } from './text-setting';
  * We are attempting to move the app away from needing settings changes to restart the app.
  * For now, this component is a holdover until such a time as we are able to fix the underlying cases. (INS-1245)
  */
```
Comment (jackkav) [inline packages/insomnia/src/ui/components/settings/general.tsx]:
```suggestion
```

**Review by jackkav — DISMISSED** [review]
