### PR TITLE
Display nicer error message given empty input when installing plugins

### LINKED ISSUE #2208: Install plugin, empty box
**Describe the bug**
handle empty input when clicking install plugin
**To Reproduce**
install, skip, preferences, plugins, install plugin
**Expected behavior**
Nicer message pointing to https://insomnia.rest/plugins/ to get the package names?
**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: macOS 10.15.4
 - Installation Method: homebrew
 - App Version v202.1.3

### PR DESCRIPTION
**Pull request by nicholasraphael**
Closes #2208 

This PR implements a nicer error message when handling empty input when clicking install plugin. It points the user to https://insomnia.rest/plugins/ to get the package names

Previous:
image

With this PR:

Screenshot 2020-06-02 15 00 17

### CODE REVIEW

**Review by develohpanda — COMMENTED** [review]
Hi @nicholasraphael! Thanks for working on this. 🤗 

My only bit of feedback would be, that we still need to indicate that plugin installation failed, and then perhaps direct them to the plugin hub.

How about something like:
> Failed to install "[plugin-name]", there may be an issue with the plugin itself. You can discover and install plugins from the [Plugin Hub](https://insomnia.rest/plugins/).

@nijikokun any thoughts on wording?

**Comment by nicholasraphael** [comment]
@develohpanda Okay that sounds good thank you. I'll wait on input from @nijikokun before making any further changes.

**Comment by nijikokun** [comment]
Awesome work so far! 

> Failed to install "[plugin-name]", there may be an issue with the plugin itself. You can discover and install plugins from the [Plugin Hub](https://insomnia.rest/plugins/).

This looks really good, just a few adjustments:

> **Failed to install "[plugin-name]"**
>
> There may be an issue with the plugin itself, as a note you can discover and install plugins from the [Plugin Hub](https://insomnia.rest/plugins/).
> <details>
> <summary>Additional Information</summary>
> <code>[error output]</code>
> </details>

❤️

**Comment by nicholasraphael** [comment]
@nijikokun just want to know if the 'Additional Information' dropdown is a priority. I feel like it would require more code additions/changes than anticipated.

**Comment by develohpanda** [comment]
> If the 'Additional Information' dropdown is a priority.

Not a priority 😄 

> I feel like it would require more code additions/changes than anticipated.

If you would like to try it, it should be fairly quick. It would involve storing the entire Error object (instead of just the error message) in State, and default that property in state to be `null` instead of `''`.

As for the collapsible component, you could use the `<details>` [HTML5 tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details). Here's an example of where that is used: https://github.com/Kong/insomnia/blob/819f4b9cf57f433378cb9620ca671e51db365067/packages/insomnia-app/app/ui/components/modals/error-modal.js#L66-L73

**Comment by nicholasraphael** [comment]
@develohpanda Thanks for the help. I have gone with the changes suggested let me know if it's good. 

Screenshot 2020-06-03 10 28 47

File: packages/insomnia-app/app/ui/components/settings/plugins.js [hunk 1]
```diff
@@ -20,7 +20,8 @@ import { showAlert, showPrompt } from '../modals';
 type State = {
   plugins: Array<Plugin>,
   npmPluginValue: string,
-  error: string,
+  error: Object,
```
Comment (develohpanda) [inline packages/insomnia-app/app/ui/components/settings/plugins.js:23]: This can be typed explicitly :)

```suggestion
  error: Error | null,
```

File: packages/insomnia-app/app/ui/components/settings/plugins.js [hunk 2]
```diff
@@ -267,7 +278,17 @@ class Plugins extends React.PureComponent<Props, State> {
             <button className="pull-right icon" onClick={this._handleClearError}>
               <i className="fa fa-times" />
             </button>
-            <div className="selectable force-pre-wrap">{error}</div>
+            <div className="selectable force-pre-wrap">
+              <b>{installPluginErrMsg}</b>
```
Comment (develohpanda) [inline packages/insomnia-app/app/ui/components/settings/plugins.js:282]: Since we can remove this from state, it can simply be:

```suggestion
              <b>Failed to install "{npmPluginValue}"</b>
```

File: packages/insomnia-app/app/ui/components/settings/plugins.js [hunk 3]
```diff
@@ -267,7 +278,17 @@ class Plugins extends React.PureComponent<Props, State> {
...
+              {`\n\nThere may be an issue with the plugin itself, as a note you can discover and install plugins from the `}
+              <a href="https://insomnia.rest/plugins/">Plugin Hub.</a>
+              <details>
+                <summary>Additionl Information</summary>
+                <pre className="pad-top-sm force-wrap selectable">
+                  <code>{error.stack || error}</code>
```
Comment (develohpanda) [inline packages/insomnia-app/app/ui/components/settings/plugins.js:288]: I suggest changing this to just show `error.message`, which was the previous behavior (where `error.message` was added to state and rendered on the UI).

```suggestion
                  <code>{error.message}</code>
```

File: packages/insomnia-app/app/ui/components/settings/plugins.js [hunk 4]
```diff
@@ -62,14 +64,16 @@ class Plugins extends React.PureComponent<Props, State> {
...
+      installPluginErrMsg: '',
     };
     try {
       await installPlugin(this.state.npmPluginValue.trim());
       await this._handleRefreshPlugins();
       newState.npmPluginValue = ''; // Clear input if successful install
     } catch (err) {
-      newState.error = err.message;
+      newState.installPluginErrMsg = `Failed to install ${this.state.npmPluginValue}`;
+      newState.error = err;
```
Comment (develohpanda) [inline packages/insomnia-app/app/ui/components/settings/plugins.js:76]: We should only need to store `error` on state, and can move the text "Failed to install..." directly into the `render()` function

```suggestion
      newState.error = err;
```

**Review by develohpanda — CHANGES_REQUESTED** [review]
Nice one! Almost there, a couple of small changes.

Namely, I don't see the need to have two items in state to represent an error; so we can remove `installPluginErrMsg` and simply put that message in the `render` itself. 😄

File: packages/insomnia-app/app/ui/components/settings/plugins.js (hunk 4 above)
Comment (nicholasraphael) [reply packages/insomnia-app/app/ui/components/settings/plugins.js:76]: @develohpanda Okay 👍 . I originally added this new state because when using `npmPluginValue` in `render()` when the `error` is displayed and user types the text changing is reflected in the error.

Comment (develohpanda) [reply packages/insomnia-app/app/ui/components/settings/plugins.js:76]: Oh I see! Makes sense. In that case this is fine. 🤗

**Review by develohpanda — APPROVED** [review]
Looks good, thanks for doing this!

I will make some minor spacing adjustments once this is merged, but the functionality is great. 💯
