### PR TITLE
fix: MCP request pane missing after switch to vertical layout

### LINKED ISSUE #9362: MCP connection parameters not visible when using vertical layout
### Expected Behavior

Image

### Actual Behavior

Image

### Reproduction Steps

1. Go to Settings > General
2. Activate "Use vertical layout" in Application section

Image

### Is there an existing issue for this?

- [x] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Which sync method do you use?

- [x] Git sync.
- [ ] Insomnia Cloud sync.
- [ ] Local only

### Additional Information

_No response_

### Insomnia Version

v12.0.0.0

### What operating system are you using?

macOS

### Operating System Version

macOS Sequoia 15.7.1

### Installation method

Downloaded from insomnia.rest

### Last Known Working Insomnia version

N/A

### PR DESCRIPTION
**Pull request by cwangsmv**
Fix MCP request pane missing after switch to vertical layout

Close https://github.com/Kong/insomnia/issues/9362 [INS-1705](https://konghq.atlassian.net/browse/INS-1705)

[INS-1705]: https://konghq.atlassian.net/browse/INS-1705?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by CurryYangxx — DISMISSED** [review]

File: packages/insomnia/src/ui/components/mcp/mcp-pane.tsx [hunk 1]
```diff
@@ -523,7 +523,9 @@ export const McpPane = () => {
               onTabChange={setRequestPaneActiveTab}
             />
           </Panel>
-          <PanelResizeHandle className="h-full w-[1px] bg-[--hl-md]" />
+          <PanelResizeHandle
+            className={direction === 'horizontal' ? 'h-full w-[1px] bg-[--hl-md]' : 'h-[1px] w-full bg-[--hl-md]'}
+          />{' '}
```
Comment (ZxBing0066) [inline packages/insomnia/src/ui/components/mcp/mcp-pane.tsx]: Is the space here added by mistake?

**Review by ZxBing0066 — APPROVED** [review]
