### PR TITLE
Tabs accessibility

### LINKED ISSUE #4942: Tabs aren't keyboard accessible.
### Expected Behavior

Hello Insomnia,

When I open a document I should be able to navigate between different tabs via keyboard (Tab, Shift + Tab, Left Arrow, Right Arrow, Up Arrow and Down Arrow).

For instance here

Screenshot 2022-07-07 at 9 45 38 PM

or here 

Screenshot 2022-07-07 at 9 47 26 PM

### Actual Behavior

Currently, this is not supported.

### Reproduction Steps

_No response_

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

_No response_

### Insomnia Version

2022.5.0-beta.2

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey

### Installation method

download from insomnia.rest

### Last Known Working Insomnia version

_No response_

### PR DESCRIPTION
**Pull request by pavkout**
changelog(Improvements): Improved overall accessibility for Tabs used throughout the App

Highlights:

* Removed the react-tabs library as dependency.
* Created a new tabs component which is a wrapper component for react-aria and react-stately library.
* Provided some extra styles for Tabs.
* Removed the button component from tab children is several components where react-tabs is used.
* Made the tabs keyboard accessible.
* Converted less css files to styled-components (tabs, markdown-editor, query-editor).

Some benefits:
In this way you have in just one file the usage of the external library and if in the future you will decide to change the external library it will be much easier.

Closes: #4942

### CODE REVIEW

**Comment by filfreire** [comment]
@pavkout would this PR still be needed in order to close #4942 ?

I noticed that if we run from latest `develop` branch, we can now use `Tab` and `Shift+Tab` to switch between tabs.

File: packages/insomnia/src/ui/components/modals/generate-config-modal.tsx [hunk 1]
```diff
@@ -119,19 +119,17 @@ export class GenerateConfigModal extends PureComponent<{}, State> {
   renderConfigTab(config: Config) {
     const linkIcon = <i className="fa fa-external-link-square" />;
     return (
-      <Tab key={config.label} tabIndex="-1">
```
Comment (pavkout) [inline packages/insomnia/src/ui/components/modals/generate-config-modal.tsx]: @filfreire Currently we sets the tabIndex to be -1 for the tab and uses html button inside tabs that's why we have this behavior pressing tab and shift+tab, but in this way we don't have arrows functionality (right arrow, left arrow, home, end button).

Please see the following link https://www.w3.org/WAI/ARIA/apg/example-index/tabs/tabs-automatic.html

Comment (filfreire) [reply packages/insomnia/src/ui/components/modals/generate-config-modal.tsx]: @pavkout understood.

Tagging @gatzjames @jackkav @dimitropoulos and @marckong to help with review.

File: packages/insomnia/src/ui/components/markdown-editor.tsx [hunk 2]
```diff
@@ -15,59 +15,71 @@ interface Props {
...
-    onChange(markdown);
-    setMarkdown(markdown);
-  }, [onChange]);
+    const handleChange = useCallback(
+      (markdown: string) => {
+        onChange(markdown);
+        setMarkdown(markdown);
+      },
+      [onChange]
+    );
```
Comment (jackkav) [inline packages/insomnia/src/ui/components/markdown-editor.tsx]: looks like these changes are formatting only, try to use vscode default formatter for now, since prettier defaults are too inconsistent.
Also it seems the e2e test is failing because tabs aren't an `li` element anymore. So the selector will need to be updated.

Comment (pavkout) [reply packages/insomnia/src/ui/components/markdown-editor.tsx]: @jackkav Thank you for the feedback, I will try to disable prettier format for now. About the e2e tests I will update them as well.

FYI: I started to investigate/implement a POC in order to replace react-tabs with react-aria tabs and to remove this extra dependency.

**Review by filfreire — APPROVED** [review]

**Review by gatzjames — COMMENTED** [review]
🚀 Looks great!

**Review by gatzjames — APPROVED** [review]

**Review by marckong — APPROVED** [review]
