### PR TITLE
fix #5969 cannot select base environment

### LINKED ISSUE #5960: Only first collection is importing.
### Expected Behavior

I wanted to export all my collections to a file, so i went to Preferences -> Data -> Export All. And it generated a file. I have no document in my project (default insomnia project),  around 10 different request collections.

Now i want to import it after reinstalling my computer. When I do, only the first collection is imported. I tried importing from different places (within a collection, or preferences-data)

When I reimport, it should have all the collections. Not just the first one.

### Actual Behavior

Only 1 out of 10 collection is importing.

It shows me 410 request will be imported, but then after that only around 7 appear, which is the first collection i ever created, all the other collections aren't there. I checked the exportfile in a text editor and i can see the request from other collections are there, but i cant import them. 

I tried different ways, either in the main menu, create - Import, or by creating a collection request and then import within that collection. None work. 

Please how to import all my collections?  File is in yaml format.

### Reproduction Steps

Start with fresh insomnia install  2023.2.0
Create multiple collections, each with requests inside (no need to create new documents or projects)
Export with Preferences - Data - Export All - to yaml file
Delete insomnia from your computer and all saves
Reinstall Insomnia 2023.2.0
Try to import your collections (any way you want).

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

_No response_

### Insomnia Version

2023.2.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Home

### Installation method

Downloaded from website

### Last Known Working Insomnia version

_No response_

### LINKED ISSUE #5969: Cannot open Base Environment
### Expected Behavior

When I open my environments to modify them ("Manage Environments" from dropdown that opens when you click the down arrow next to the currently active environment name in the top left of the UI) I am shown the currently active environment. I should be able to click the "Base Environment" to modify shared variables.

### Actual Behavior

I can no longer open the base Environment. When I click it:

image

Nothing happens. The cursor _does_ change to indicate clickability. The actual click does nothing.

### Reproduction Steps

1. Open a collection containing a base environment and sub environments, with the sub environment active.
2. Click the down arrow next to the active environment name.
3. Select "Manage Environments"
4. Click "Base Environment"

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

The workaround for this that I just discovered is selecting 'No Environment' then opening the environment management. This works until you click a sub-environment (which works). After which you're back in the same buggy state.

This is the output of the About window:

[Window Title]
Insomnia

[Main Instruction]
Insomnia

[Content]
Version: Insomnia 2023.2.1
Build date: 5/15/2023
OS: Windows_NT x64 10.0.22621
Electron: 22.0.0
Node: 16.17.1
V8: 10.8.168.20-electron.0
Architecture: x64

[OK] [Copy]

### Insomnia Version

2023.2.1

### What operating system are you using?

Windows

### Operating System Version

Windows_NT x64 10.0.22621

### Installation method

Download from Insomnia rest

### Last Known Working Insomnia version

Whatever version this was last night before it auto-updated without asking.

### PR DESCRIPTION
**Pull request by filfreire**
Closes #5969 

changelog(Fixes): Fixed a regression where folks could no longer open the base environment on the Environments Editor

### CODE REVIEW

File: packages/insomnia/src/ui/components/modals/workspace-environments-edit-modal.tsx [hunk 1]
```diff
@@ -354,7 +354,8 @@ export const WorkspaceEnvironmentsEditModal = forwardRef<WorkspaceEnvironmentsEd
           >
             <button
               onClick={() => {
-                if (environmentEditorRef.current?.isValid() && selectedEnvironmentId === baseEnvironment?._id) {
+                if (environmentEditorRef.current?.isValid() && selectedEnvironmentId !== baseEnvironment?._id) {
+                  // @ts-expect-error -- ??
                   setState(state => ({
```
Comment (gatzjames) [inline packages/insomnia/src/ui/components/modals/workspace-environments-edit-modal.tsx]:
```suggestion
baseEnvironment?.id && setState(state => ({
```

**Review by gatzjames — APPROVED** [review]
We could remove the ts expect error by adding a check left a suggestion. Lgtm
