### PR TITLE
Fix for warning not displaying when using an environment variable with '-'

### LINKED ISSUE #2207: Environment Keys does not allow "-" in their names
**Describe the bug**
If a key in environment overrides contains "-", it causes following error.
```
Error: Couldn't resolve host name
```

**To Reproduce**
1. Right-click on any of the folders on the left-hand side.
2. Click on **Environment**
3. Add following key-value pair to the window that opened:
```
  "GOOGLE-UK": "https://google.co.uk"

```
4. Click Done, and create a new request in that folder
5. Paste **{{ GOOGLE-UK }}** on Address Bar (i.e where URL is typed) and choose Environment Variable
6. Click Send

**Expected behavior**
You will see following error:

image

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6
 - Installation Method: download
 - App Version Version 7.1.1 (7.1.1.3350)

### PR DESCRIPTION
**Pull request by Vorashil**
This is a follow up to this bug report (closes #2207). I would suggest reading this bug report before reading the rest of this message.

I figured dash ( "-" )should not be allowed in environmental variables, as I found the error message saying that "_Keys must only contain letters, numbers, and underscores_".

image

Nevertheless, this ```if (!key.match(...))```  block never shows this error message when a user is using illegal characters. It was due to ```Object.keys(value)``` part.

```value``` is an object of EnvironmentInfo class. 
```
export type EnvironmentInfo = {
  object: Object,
  propertyOrder: Object | null,
};
```
So, ```Object.keys(value)``` returns ["object", "propertyOrder"]. However, Environment variables are stored as key-value pairs in the ```object``` field of  ```EnvironmentInfo``` class. So to check keys in environmental variables I needed to change 
``` 
Object.keys(value)
```
to
``` 
Object.keys(value.object)
```

### CODE REVIEW

File: packages/insomnia-app/app/ui/components/editors/environment-editor.js [hunk 1]
```diff
@@ -54,7 +54,7 @@ class EnvironmentEditor extends React.PureComponent<Props, State> {
 
     // Check for invalid key names
     if (value) {
```
Comment (develohpanda) [inline packages/insomnia-app/app/ui/components/editors/environment-editor.js]: Looks like this condition should also be updated

```suggestion
    if (value && value.object) {
```

**Review by develohpanda — CHANGES_REQUESTED** [review]
Thanks for looking into this! One small change, otherwise it's good.

Note: I'm going to update the PR title to reflect this change; there are similar issues (#1666 and #456) with more discussion around catering for `-` in an environment variable (and why it currently doesn't work).

Fixing the warning message is good for now, as support for `-` is a little more complex :)

File: packages/insomnia-app/app/ui/components/editors/environment-editor.js (hunk 1 above)
Comment (Vorashil) [reply packages/insomnia-app/app/ui/components/editors/environment-editor.js]: done

**Review by develohpanda — APPROVED** [review]
Not sure why GH didn't run tests, but this passed locally and brought the warning behavior back. 💯
