### PR TITLE
Environment Rendering Improvements

### LINKED ISSUE #350: [Bug] Template variable 'now' behaves strangely
## Overview
- `Insomnia Version:` 5.5.2
- `Operating System:`  Windows
- `Summary: ` "now" is inconsistently processed by the filters. Preview on hover works as expected, but the real request is broken.

## How To Reproduce
Example: POST request with JSON body.
```
{
	"t1": "{{now}}",
	"t2": "{{now | urlencode}}",
	"t3": "{{now | replace('Z', '+0000')}}",
	"t4": "{% now 'custom', 'YYYY-MM-DDTHH:mm:ssZZ' %}"
}
```
Rendered like this:
```
> POST / HTTP/1.1
> Host: localhost
> User-Agent: insomnia/5.5.2
> Accept: */*
> Accept-Encoding: deflate, gzip
> Content-Type: application/json
> Content-Length: 152
| {
| 	"t1": "2017-07-10T17:30:56.297Z",
| 	"t2": "%7B%25%20now%20'ISO-8601'%20%25%7D",
| 	"t3": "2017-07-10T17:30:56.297Z",
| 	"t4": "2017-07-10T20:30:56+0300"
| }
```
It seems, "now" is fed to the filters as a literal value, not a substituted timestamp.
{% now %} works as expected (but cannot be used with filters?).

### PR DESCRIPTION
**Pull request by gschier**
## What

This PR makes a few changes and fixes to the render pipeline to address some bugs and improve usability.

- [x] Now pass metadata in when rendering environment
  - Render consists of two phases (build and render environment, render request)
  - Metadata like active request/workspace didn't used to be passed to first stage
- [x] Handle render failures for unused environment variables better
  - used to do it by only rendering variables when rendering environment initially
  - now do it by trying to render environment variables and leaving them as-is if exception thrown
    - these exceptions will re-emerge at the second stage if the variable is actually used
    - this also addresses the case where a variable was set to a tag, then used in a filter (Fixes #350) 
- [x] Modify the cookie tag to show valid cookie names if specified one doesn't exist
   image
- [x] Now show `"Environment"` in rendered error path if failure occurs there
   image

### CODE REVIEW

File: app/common/render.js [hunk 1]
```diff
@@ -153,15 +166,22 @@ export async function getRenderContext (request, environmentId, ancestors = null
   const rootEnvironment = await models.environment.getOrCreateForWorkspace(workspace);
   const subEnvironment = await models.environment.getById(environmentId);
 
-  // Generate the context we need to render
-  const context = await buildRenderContext(ancestors, rootEnvironment, subEnvironment, variablesOnly);
-
-  // Add meta data
-  context.getMeta = () => ({
+  // Add meta data helper function
+  const baseContext = {};
```
Comment (gschier) [inline app/common/render.js]: This is where the magic happens. The rest of the changes aren't very meaningful.
