### PR TITLE
[regression] reverts sort order callback behavior

### LINKED ISSUE #4191: Sorting request sidebar doesn't work on 2021.6
### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for a bug that matches the one I want to file, without success.

### Insomnia Version

2021.6.0

### What operating system are you using?

macOS

### Operating System Version

macOS Big Sur 11.5.2

### Installation method

Insomnia.rest

### Last Known Working Insomnia version

NA

### Expected Behavior

Expecting to be able to sort requests and collections/folders by name.

### Actual Behavior

Sort buttons don't appear to do anything.

https://www.screencast.com/t/vh5ww6rA1a

### Reproduction Steps

Deleted old version of Insomnia.app
Installed Insomnia rest client from web (https://insomnia.rest/)

### Additional Information

Version: Insomnia 2021.6.0
Release date: 28/10/2021
OS: Darwin x64 20.6.0
Electron: 11.2.3
Node: 12.18.3
V8: 8.7.220.31-electron.0
Architecture: x64
node-libcurl: libcurl/7.73.0 OpenSSL/1.1.1k zlib/1.2.11 brotli/1.0.9 zstd/1.4.9 libidn2/2.1.1 libssh2/1.9.0 nghttp2/1.42.0

### PR DESCRIPTION
**Pull request by dimitropoulos**
closes INS-1107
closes #4191

see: https://www.loom.com/share/c422ef5cd42d4d899668105c572b931f

Unfortunately, we were bitten by the Dropdown family yet again.  Except this time, it's that and the combination of very extensive prop drilling.

There are a few things that happened.  This PR reverts to the original behavior since day one:

https://github.com/Kong/insomnia/commit/c50bc1f965eba7c1ad9514840c2bea588e7f4a47#diff-916959cd385131affe2abf2f190250982a3df3c5819020ba515eec08fdeb6577R19

___

What happened here is that the the logic for the sorting lives in `App.tsx` in a function called `_sortSidebar`

here's the implementation.  note the signature and what it does with the 2nd argument:
```ts
  async _sortSidebar(order: SortOrder, parentId?: string) {
    let flushId: number | undefined;

    if (!this.props.activeWorkspace) {
      return;
    }

    if (!parentId) {
      parentId = this.props.activeWorkspace._id;
      flushId = await db.bufferChanges();
    }

    const docs = [
      ...(await models.requestGroup.findByParentId(parentId)),
      ...(await models.request.findByParentId(parentId)),
      ...(await models.grpcRequest.findByParentId(parentId)),
    ].sort(sortMethodMap[order]);
    await this._recalculateMetaSortKey(docs);
    // sort RequestGroups recursively
    await Promise.all(docs.filter(isRequestGroup).map(g => this._sortSidebar(order, g._id)));

    if (flushId) {
      await db.flushChanges(flushId);
    }
  }
```

### Prop Drill 1

Then `App` passes a reference to `_sortSidebar` to `Wrapper` in a prop, `handleSidebarSort`

### Prop Drill 2

Take note that the signature changes at the level of Wrapper, it's hardcoded like this:
```ts
interface WrapperProps {
  ...
  handleSidebarSort: (sortOrder: SortOrder) => void;
}
```

Then `Wrapper` passes it to `WrapperDebug` without modification

### Prop Drill 3

Note that in `WrapperDebug` it's hardcoded again (also wrong)

`WrapperDebug` then passes it's prop `handleSidebarSort` to `SidebarFilter` unchanged, but it renames it to the prop `sidebarSort` just for fun.

### Prop Drill 4

`SidebarFilter` again, for the 3rd time, hardcodes the signature (wrongly) and `sidebarSort` is passed to `SidebarSortDropdown` unchanged

### Prop Drill 5

`SidebarSortDropdown` hardcodes the signature a 4th time (wrong, again), then it passes this reference to `DropdownItem` as `onClick`

### Prop Drill 6

We've finally reached our destination.  Internally, `DropdownItem` uses `_handleClick`, which is implemented like this:

```ts
  _handleClick(e) {
    const { stayOpenAfterClick, onClick, disabled } = this.props;

    if (stayOpenAfterClick) {
      e.stopPropagation();
    }

    if (!onClick || disabled) {
      return;
    }

    if (this.props.hasOwnProperty('value')) {
      onClick(this.props.value, e);
    } else {
      onClick(e);
    }
  }
```

See the issue?  It passes `e` as the second argument.  Well, if you look back at the second argument above, you'll see that we do `findByParentId(parentId)`.   This means we're going to be passing an event here, and not a string of a parentId.  :)

### CODE REVIEW

File: packages/insomnia-app/app/common/constants.ts [hunk 1]
```diff
@@ -305,7 +305,7 @@ export const SORT_ORDERS = [
   SORT_HTTP_METHOD,
   SORT_TYPE_DESC,
   SORT_TYPE_ASC,
-];
+] as const;
```
Comment (dimitropoulos) [inline packages/insomnia-app/app/common/constants.ts:308]: (otherwise you'd get `Argument of type 'string' is not assignable to parameter of type 'SortOrder'.`)

**Review by develohpanda — APPROVED** [review]
Wow this is rough, but great find 🔥
