### PR TITLE
🚀 Hotfix 2021.4.1 RC

### LINKED ISSUE #3777: Export did not work anymore in version 2021.4.0
**Describe the bug**
When exporting the insomnia configuration it does not export a valid json file and the extension is now `.null` with a content of `undefined`.

**To Reproduce**
1. To start, click the dropdown arrow next to workspace name and select ‘Import/Export’.
2. Click the ‘Export Data’ dropdown and click ‘Current Workspace’.
3. Select which (if not all) requests you’d like to export and click the ‘Export’ button.
4. Select ‘Insomnia v4 (JSON)’ and click ‘Done’.

**Expected behavior**
A valid .json file

**Screenshots**
image

**Desktop:**
 - OS: Microsoft Windows 10 Pro Versión 10.0.19042 compilation 19042
 - Installation Method: Installer
 - App Version 2021.4.0

**Additional context**
Yesterday, before the update, it was possible to export without problems.

### PR DESCRIPTION
**Pull request by develohpanda**
Closes #3777 

https://github.com/Kong/insomnia/compare/core@2021.4.0...core@2021.4.1

### CODE REVIEW

File: packages/insomnia-app/app/ui/redux/modules/global.tsx [hunk 1]
```diff
@@ -698,6 +705,9 @@ export const exportRequestsToFile = (requestIds: string[]) => async dispatch =>
             'json',
           );
           break;
+
+          default:
+            unreachableCase(`selected export format "${selectedFormat}" is invalid`);
```
Comment (develohpanda) [inline packages/insomnia-app/app/ui/redux/modules/global.tsx]:
```suggestion
            unreachableCase(selectedFormat, `selected export format "${selectedFormat}" is invalid`);
```

File: packages/insomnia-app/app/ui/redux/modules/global.tsx [hunk 2]
```diff
@@ -599,6 +603,9 @@ export const exportWorkspacesToFile = (workspaceId: string | undefined = undefin
               'json',
             );
             break;
+
+          default:
+            unreachableCase(`selected export format "${selectedFormat}" is invalid`);
```
Comment (dimitropoulos) [inline packages/insomnia-app/app/ui/redux/modules/global.tsx]:
```suggestion
            unreachableCase(selectedFormat, `selected export format "${selectedFormat}" is invalid`);
```

we need it here too @develohpanda

Comment (develohpanda) [reply packages/insomnia-app/app/ui/redux/modules/global.tsx]: oh!

**Review by dimitropoulos — APPROVED** [review]
