### PR TITLE
Request URL bar fix and collection name truncation improvement

### LINKED ISSUE #7029: Unable to see full collection names
### Expected Behavior

image

For collection with longer names, I expect to see the collection name when I hover over the collection.  At the moment, I have to click into the collection and go to Preferences to see the collection name.  

### Actual Behavior

When more than 1 collection share a similar name that long, it's very difficult to see the full name of the collection.

### Reproduction Steps

Create two collections with similar long names and try to tell them apart in the Insomnia window.  

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

_No response_

### Insomnia Version

8.6

### What operating system are you using?

macOS

### Operating System Version

Ventura

### Installation method

insomnia.rest

### Last Known Working Insomnia version

_No response_

### LINKED ISSUE #7221: Pressing enter/return while text is selected in the request URL bar causes the selected text to be deleted
### Expected Behavior

Pressing enter/return while text is selected in the request URL bar should not modify the request URL bar's value.

### Actual Behavior

Pressing enter/return while text is selected in the request URL bar causes the request to send (as expected), however it also deletes any text that was selected.

### Reproduction Steps

1. Create a new request (e.g. HTTP)
2. Enter something into the request URL bar
3. Select a portion or all of the text that you entered
4. Press enter/return to send the request
5. Observe that the text you selected in Step 3 was deleted

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

I've attached a short screen recording that demonstrates this bug.
https://github.com/Kong/insomnia/assets/132221630/bf35760c-2c37-4712-a5f9-4b07bfc56482

This might be happening due to Insomnia treating enter/return as a literal carriage return or newline character, thereby replacing whatever text was selected with a carriage return or newline character. That's just a guess though.
If it _is_ due to that, the whole field should probably ignore that kind of character as it's a single-line text field.

You may notice, by the way, that even though part of the hostname that was entered was deleted, the request was still sent to the correct URL (hence the 200 response). To clarify, this is because the text is getting deleted immediately after the request gets sent.. not before (despite the fact that it looks like both are happening at the same time). This is why in the above screen recording, I then resent the request a second time after the text was deleted - to demonstrate that the text was indeed deleted.

### Insomnia Version

8.6.1

### What operating system are you using?

macOS

### Operating System Version

macOS Sonoma 14.3.1 (23D60)

### Installation method

Downloaded from official insomnia.rest website

### Last Known Working Insomnia version

_No response_

### PR DESCRIPTION
**Pull request by git-commit-amen**
Closes #7221: Pressing enter/return while text is selected in the request URL bar causes the selected text to be deleted
- Fixed 'paste' handling code which was causing text replacement logic to run when text had merely been selected but not actually changed

Closes #7029: Unable to see full collection names
- Added title (hover tooltip) for name label on collection card

### CODE REVIEW

**Comment by subnetmarco** [comment]
Thanks for the contribution, we will review it soon.

**Comment by git-commit-amen** [comment]
Hi there @subnetmarco, anything I can do to assist with this one? Happy to help if you have any further questions on it.
Thanks heaps!

**Review by filfreire — DISMISSED** [review]
Tested locally LGTM

File: packages/insomnia/src/ui/components/codemirror/one-line-editor.tsx [hunk 1]
```diff
@@ -109,7 +109,7 @@ export const OneLineEditor = forwardRef<OneLineEditorHandle, OneLineEditorProps>
     codeMirror.current.on('beforeChange', (_: CodeMirror.Editor, change: CodeMirror.EditorChangeCancellable) => {
       const isPaste = change.text && change.text.length > 1;
       if (isPaste) {
-        if (change.text[0].startsWith('curl')) {
+        if (change.text[0].startsWith('curl') || !change.text.join('').trim()) {
```
Comment (jackkav) [inline packages/insomnia/src/ui/components/codemirror/one-line-editor.tsx]: Thanks @git-commit-amen the intent could be a bit clearer though.
```suggestion
        const startsWithCurl = change.text[0].startsWith('curl');
        const isWhitespace = change.text.join('').trim();
        if (startsWithCurl || !isWhitespace) {
```

**Review by jackkav — APPROVED** [review]

File: packages/insomnia/src/ui/components/codemirror/one-line-editor.tsx (hunk 1 above)
Comment (git-commit-amen) [reply packages/insomnia/src/ui/components/codemirror/one-line-editor.tsx]: Good pickup - yeah I agree. Will keep clarity in mind for any future commits. Thanks!
