### PR TITLE
[o2k] fix: kubernetes TLS implementation is (very) wrong

### LINKED ISSUE #3394: openapi-2-kong package generates invalid ingress spec with x-kubernetes-tls present
**Describe the bug**
While using the kong-kubernetes-config:v2.2.35 plugin for Insomnia when adding the `x-kubernetes-tls` key and configuration to the root server block, the plugin generates the ingress tls spec under the ingress rules.  The Kubernetes api schema for `extensions/v1beta1`(which is the apiVersion the plugin generates for `Kind: Ingress`) expects tls to present at `spec.tls` and not `spec.rules.tls`

**To Reproduce**
Use the following yaml to generate kubernetes spec.
```
openapi: 3.0.2
##############################
## API Information Document ##
##############################
info:
  # Define the Default Ingress metadata and annotations for Kubernetes
  x-kubernetes-ingress-metadata:
    name: my cloud-api
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      external-dns.alpha.kubernetes.io/hostname: myserver
      konghq.com/strip-path: "true"
  title: my Cloud API
  version: "1.0.0"
  contact:
    name: myserver Support
    url: https://myserver/support
    email: support@myserver
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
###################################
## Kong Plugins for all requests ##
###################################
# OpenID Connect Plugin for Kong API Authorization with Keycloak
x-kong-plugin-openid-connect:
    name: openid-connect
    enabled: true
    config:
      issuer: <keycloak-realm-auth-endpoint>
      client_id:
        - <client-id>
      client_secret:
        - <client-secret>
      auth_methods: ["authorization_code", "bearer", "session", "refresh_token"]
      session_cookie_name: "cookie-name"
      refresh_token_param_name: "Offline-Token"
      scopes: ["openid", "profile", "email"]
      upstream_user_info_header: "x-userinfo"
      upstream_access_token_header: "access-token-name"
# Enable HTTPS redirect to disable HTTP access for the API server
x-kong-plugin-https-redirect:
  name: pre-function
  config:
    functions:
    - |
      local scheme = kong.request.get_scheme()
      if scheme == "http" then
        local host = kong.request.get_host()
        local query = kong.request.get_path_with_query()
        local url = "https://" .. host ..query
        kong.response.set_header("Location",url)
        return kong.response.exit(302,url)
      end
#############
## Servers ##
#############
servers:
- url: https://myserver/v1
  description: The non-production API Server for FRED Studio
  x-kubernetes-tls:
    hosts:
      - myserver
    secretName: myserver-tls
################
## Components ##
################
components:
  # Security Schemes
  securitySchemes:
    StudioOIDC:
      type: openIdConnect
      openIdConnectUrl: <well-known-config>
      ## Required Scopes defined at the Operation Level ##
  schemas:
  # define schemas here for components
    # Schema for error response body
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
#############################
## Environment API Schemas ##
#############################
    Quotas:
      type: object
      properties:
        quotas:
          type: object
        runningNodes:
          type: object
        queuedBatches:
          type: object
#######################
## Batch API Schemas ##
#######################
    # Model Upload URL Request Schema
    BatchModelUploadRequest:
      type: object
      properties:
        modelName:
          type: string
    # Model Upload URL Response Schema
    BatchModelUploadResponse:
      type: object
      properties:
        url:
          type: string
    # Batch Submit Request Schema
    BatchSubmitRequest:
      type: object
      properties:
        batchGuid:
          type: string
        computeSize:
          type: string
        containerLogLevel:
          type: string
        killTime:
            type: integer
        cliCommand:
          type: string
        batchConfig:
          type: object
    # Batch Submit Response Schema
    BatchSubmitResponse:
      type: object
      properties:
        message:
          type: string
    # Batch Get Logs Request Schema
    BatchGetLogsRequest:
      type: object
      properties:
        batchGuid:
          type: string
        limit:
          type: string
        interval:
          type: string
    # Batch Get Logs Response Schema
    BatchGetLogsResponse:
      type: object
      properties:
        # results is an array of objects containing the log entries
        results:
          type: array
          items:
            type: object
    # Batch Get Results Request Schema
    BatchGetResultsRequest:
      type: object
      properties:
        fredResultsKey:
          type: string
    # Batch Get Results Response Schema
    BatchGetResultsResponse:
      type: object
      properties:
        url:
          type: string
    # Batch Get Status Request Schema
    BatchGetStatusRequest:
      type: object
      properties:
        batchGuid:
          type: string
    # Batch Get Status Response Schema
    BatchGetStatusResponse:
      type: object # Not entirely sure what all is being returned here, but I know it's an object!
    # Batch Validate Config Request Schema
    BatchValidateConfigRequest:
      type: object
      properties:
        batchConfig:
          type: object
    # Batch Validate Config Response Schema
    BatchValidateConfigResponse:
      type: object
      properties:
        message:
          type: string
  # define query parameters here
  # parameters: # No Parameters defined yet
  # construct default responses here
  responses:
    NotFound:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    GeneralError:
      description: General Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
##############################
## Paths and API Operations ##
##############################
paths:
####################
## Root API Paths ##
####################
  '/offline-portal':
    x-kong-plugin-aws-lambda:
      name: aws-lambda
      config:
        aws_key: <iam-lambda-user-accesskey>
        aws_secret: <iam-lambda-user-secretkey>
        aws_region: us-east-1
        function_name: <offline-token-function>
        timeout: 60000
        keepalive: 60000
        port: 443
        forward_request_headers: true
    get:
      operationId: getOfflineToken
      description: Returns an Offline Token to be consumed by the myserver CLI
      security:
        - StudioOIDC:
            # An array of required scopes for the Operation
            - offline_access # This is created through Keycloak to enforce different levels of authorization (Scope Defined)
      responses:
        '200':
          description: Offline-Token Portal
  '/user-info':
    x-kong-plugin-aws-lambda:
      name: aws-lambda
      config:
        aws_key: <iam-lambda-user-accesskey>
        aws_secret: <iam-lambda-user-secretkey>
        aws_region: us-east-1
        function_name: <user-info-function>
        timeout: 60000
        keepalive: 60000
        port: 443
        forward_request_headers: true
    get:
      description: myserver API User-Info
      operationId: getUserInfo
      summary: Returns the User Info from the x-userinfo header forwarded upstream by Kong
      security:
        - StudioOIDC:
          # an array of scopes required to perform the operation
            - fred_read # This is created through Keycloak to enforce different levels of authorization (Scope not yet defined)
      responses:
        '200':
          description: myserver API User Profile
```

The full output from the plugin is: 
```
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: get-method
route:
  methods:
    - get
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: add-openid-connect-g0
plugin: openid-connect
config:
  issuer: <keycloak-realm-auth-endpoint>
  client_id:
    - <client-id>
  client_secret:
    - <client-secret>
  auth_methods:
    - authorization_code
    - bearer
    - session
    - refresh_token
  session_cookie_name: cookie-name
  refresh_token_param_name: Offline-Token
  scopes:
    - openid
    - profile
    - email
  upstream_user_info_header: x-userinfo
  upstream_access_token_header: access-token-name
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: add-pre-function-g1
plugin: pre-function
config:
  functions:
    - |
      local scheme = kong.request.get_scheme()
      if scheme == "http" then
        local host = kong.request.get_host()
        local query = kong.request.get_path_with_query()
        local url = "https://" .. host ..query
        kong.response.set_header("Location",url)
        return kong.response.exit(302,url)
      end
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: add-aws-lambda-p2
plugin: aws-lambda
config:
  aws_key: <iam-lambda-user-accesskey>
  aws_secret: <iam-lambda-user-secretkey>
  aws_region: us-east-1
  function_name: <offline-token-function>
  timeout: 60000
  keepalive: 60000
  port: 443
  forward_request_headers: true
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: add-openid-connect-m3
plugin: openid-connect
config:
  issuer: <well-known-config>
  scopes_required:
    - offline_access
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: add-aws-lambda-p4
plugin: aws-lambda
config:
  aws_key: <iam-lambda-user-accesskey>
  aws_secret: <iam-lambda-user-secretkey>
  aws_region: us-east-1
  function_name: <user-info-function>
  timeout: 60000
  keepalive: 60000
  port: 443
  forward_request_headers: true
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: add-openid-connect-m5
plugin: openid-connect
config:
  issuer: <well-known-config>
  scopes_required:
    - fred_read
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-cloud-api-0
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    external-dns.alpha.kubernetes.io/hostname: myserver
    konghq.com/strip-path: "true"
    konghq.com/plugins: add-openid-connect-m3, add-aws-lambda-p2, add-pre-function-g1
    konghq.com/override: get-method
    kubernetes.io/ingress.class: kong
spec:
  rules:
    - host: myserver
      tls:
        paths:
          - path: /v1/offline-portal
            backend:
              serviceName: my-cloud-api-service-0
              servicePort: 443
        hosts:
          - myserver
        secretName: myserver-tls
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-cloud-api-1
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    external-dns.alpha.kubernetes.io/hostname: myserver
    konghq.com/strip-path: "true"
    konghq.com/plugins: add-openid-connect-m5, add-aws-lambda-p4, add-pre-function-g1
    konghq.com/override: get-method
    kubernetes.io/ingress.class: kong
spec:
  rules:
    - host: myserver
      tls:
        paths:
          - path: /v1/user-info
            backend:
              serviceName: my-cloud-api-service-0
              servicePort: 443
        hosts:
          - myserver
        secretName: myserver-tls
```

Paying close attention to this output:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-cloud-api-1
spec:
  rules:
    - host: myserver
      tls:
        paths:
          - path: /v1/user-info
            backend:
              serviceName: my-cloud-api-service-0
              servicePort: 443
        hosts:
          - myserver
        secretName: myserver-tls
```
We can see that tls configuration is mixed in with the ingress rules.  This is an invalid Kubernetes configuration and will be rejected by the server.

**Expected behavior**

The expected Ingress Output would be:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-cloud-api-1
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    external-dns.alpha.kubernetes.io/hostname: myserver
    konghq.com/strip-path: "true"
    konghq.com/plugins: add-openid-connect-m5, add-aws-lambda-p4, add-pre-function-g1
    konghq.com/override: get-method
    kubernetes.io/ingress.class: kong
spec:
  tls:
    hosts:
      - myserver
    secretName: myserver-tls
  rules:
    - host: myserver
      http:
        paths:
          - path: /v1/user-info
            backend:
              serviceName: my-cloud-api-service-0
              servicePort: 443
```

**Desktop (please complete the following information):**
 - OS: Linux 5.8.0-53-generic #60~20.04.1-Ubuntu
 - Installation Method: debian package manager
 - App Version: v2021.3.0

**Additional context**
I was able to do a quick rewrite of the openapi-2-kong package locally to fix the output, and I will open a PR to address the issue later today hopefully.
Cheers!

### PR DESCRIPTION
**Pull request by dimitropoulos**
closes: INS-734
closes: https://github.com/Kong/insomnia/issues/3394

Wow.  There are a few things here that really need attention.

Here are the steps as I see them:
- correct the types to reflect the actual API (linking to the API Reference)
- fix whatever that broke (which will fix the issue @jessicuzwhynot raised)
- validate the output of all tests (I've only used `kubeval` in the past, but we'll have to find something that works in node-land, which is probably doable because there's a reliable OpenAPI spec for all kubernetes resources)
- use something to get TypeScript types from the OpenAPI official spec

### CODE REVIEW

**Comment by dimitropoulos** [comment]
@jessicuzwhynot please take a look.  This should be ready to go.  I set up fixture tests for `kong-for-kubernetes`, which we badly needed, so thanks for providing the full input/output.

I will note one _other_ thing we were doing significantly wrong in the past: on the ingress resource, `spec.tls` is an array
Screenshot_20210521_090025

which means this change is necessary to your `x-kubernetes-tls`:
Screenshot_20210521_090109

And the resulting spec (for the one you gave, for example) will be:
```
  - apiVersion: extensions/v1beta1
    kind: Ingress
    metadata:
      name: my-cloud-api-1
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        external-dns.alpha.kubernetes.io/hostname: myserver
        konghq.com/strip-path: "true"
        konghq.com/plugins: add-openid-connect-m5, add-aws-lambda-p4, add-pre-function-g1
        konghq.com/override: get-method
        kubernetes.io/ingress.class: kong
    spec:
      tls:
        - hosts:
            - myserver
          secretName: myserver-tls
      rules:
        - host: myserver
          http:
            paths:
              - path: /v1/user-info
                backend:
                  serviceName: my-cloud-api-service-0
                  servicePort: 443
```

Since this was already literally useless in the past, I'm not sure it even matters that we need to make this change because specifying `x-kuberenetes-tls` did _nothing_ in the past anyway, since what it was outputting was in the completely wrong place (and therefore ignored by kubernetes anyway).

**Comment by jessicuzwhynot** [comment]
@dimitropoulos Yes!  That looks correct.  Toying with it locally was my first "real" foray into Typescript/JS, and I wasn't able to get it to return an array properly.  My version kept returning 
```spec:
      tls:
        - - hosts:
            - myserver
          secretName: myserver-tls
```
whenever I specified it as 
```
x-kubernetes-tls:
  - hosts:
    - myserver
    secretName: myserver-tls
```
So I was just defining it as an object in the OAS spec, with `hosts` as an array, to meet my needs at the time.
```
export interface K8sTlsSpec {
  hosts: string[];
  secretName: string;
}

export interface K8sSpec {
  tls?: K8sTlsSpec;
  rules: K8sIngressRule[];
}
// doc
const generateDoc = function() {
          const tlsConfig = generateTlsConfig(sp.server);
          if (tlsConfig) {
            const doc: KubernetesConfig = {
              apiVersion: 'extensions/v1beta1',
              kind: 'Ingress',
              metadata,
              spec: {
                tls: tlsConfig,
                rules: [generateRulesForServer(serverIndex, sp.server, specName, [pp.path])],
              },
            };
            return doc;
          }
```

This looks great, thanks so much for taking action on this!

**Comment by dimitropoulos** [comment]
Great, thanks for confirming - that's very helpful.  We'll try to get this out as soon as possible.  I don't think it'll make the upcoming 4.0 release, but maybe we can add it or release it in a patch.

Just one more question, is your main use-case:
1. using insomnia (the electron app)
1. using `inso` (the cli)
1. using `openapi-2-kong` (the npm package)

**Review by jessicuzwhynot — APPROVED** [review]
This all looks great.

**Comment by jessicuzwhynot** [comment]
> Great, thanks for confirming - that's very helpful. We'll try to get this out as soon as possible. I don't think it'll make the upcoming 4.0 release, but maybe we can add it or release it in a patch.
> 
> Just one more question, is your main use-case:
> 
> 1. using insomnia (the electron app)
> 2. using `inso` (the cli)
> 3. using `openapi-2-kong` (the npm package)

My main use case is using the electron app for now.  My ultimate endgoal is to integrate the npm package into our backend AWS lambda repository, and compile and deploy any changes to the API with CI workflows.

On another note, did you by chance happen to work on the first pass of the enterprise OIDC plugin ~late 2017 - early 2018?  I feel like I remember your name from a shared slack channel / meetings while I was at Cisco

**Comment by dimitropoulos** [comment]
> My ultimate endgoal is to integrate the npm package into our backend AWS lambda repository, and compile and deploy any changes to the API with CI workflows.

That's very useful feedback, thanks!  I asked specifically for that reason - because I want to make sure that the library is fit for the 3rd case's use - the npm library outside of the context of insomnia or `inso`.  And hey, if you need any assistance with that, please feel free to drop me a line.  It's important for us to understand how people are using this so we can make it as useful as possible for the main use-cases.

> On another note, did you by chance happen to work on the first pass of the enterprise OIDC plugin ~late 2017 - early 2018?

Nope, sorry. :)

File: packages/openapi-2-kong/src/types/kubernetes-config.ts [hunk 1]
```diff
@@ -19,39 +19,49 @@ export type K8sAnnotations =
   & Record<string, string>
   ;
 
+/** see: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.21/#objectmeta-v1-meta */
```
Comment (develohpanda) [inline packages/openapi-2-kong/src/types/kubernetes-config.ts:23]: Thanks for adding these 👍🏽

File: packages/openapi-2-kong/src/types/kubernetes-config.ts [hunk 2]
```diff
@@ -62,7 +72,7 @@ export interface K8sMethodConfig {
   };
 }
 
-export interface K8sPluginConfig {
+export interface K8sKongPlugin {
```
Comment (develohpanda) [inline packages/openapi-2-kong/src/types/kubernetes-config.ts:78]: Docs for the Kong specific ones are here but even this feels incomplete 🤔  https://docs.konghq.com/kubernetes-ingress-controller/1.2.x/concepts/ingress-classes/

File: packages/openapi-2-kong/src/kubernetes/plugin-helpers.ts [hunk 3]
```diff
@@ -56,14 +58,14 @@ export const dummyPluginDoc = (suffix: string): K8sKongPlugin => ({
   plugin: 'dummy-thing',
 });
 
-export const methodDoc = (method: string) => ({
+export const methodDoc = (method: HttpMethodType | Lowercase<HttpMethodType>): K8sKongIngress => ({
```
Comment (develohpanda) [inline packages/openapi-2-kong/src/kubernetes/plugin-helpers.ts:61]: TIL `Lowercase<T>` is a thing

File: packages/openapi-2-kong/src/declarative-config/plugins.ts [hunk 4]
```diff
@@ -118,9 +106,9 @@ function generateBodyOptions(
 
 export function generateRequestValidatorPlugin(
   plugin: Record<string, any>,
-  operation: OA3Operation | typeof undefined,
-  tags: string[],
-): DCPlugin {
+  operation?: OA3Operation,
+  tags?: string[],
```
Comment (develohpanda) [inline packages/openapi-2-kong/src/declarative-config/plugins.ts:110]: Only one note - tags should/will be defined (even as an empty array) from the entry point in `generate.ts`, to avoid having to default them throughout the code

File: packages/openapi-2-kong/src/types/declarative-config.ts [hunk 5]
```diff
@@ -1,13 +1,16 @@
...
   body_schema?: string;
   issuer?: string;
   key_names?: string[];
-  parameter_schema?: string;
+  parameter_schema?: OA3Parameter[];
   scopes_required?: string[];
   verbose_response?: boolean;
-  version?: 'draft4',
+  version?: 'draft4';
+  [key: string]: any;
```
Comment (develohpanda) [inline packages/openapi-2-kong/src/types/declarative-config.ts:13]: Do you see this as a generic collection of configs allowed by all plugins? some of them (`allowed_content_types`, `body_schema` and `parameter_schema`) are specific only to the request validator plugin because it has a special-cased implementation. Not sure how I feel about a catch-all plugin config type in this way

File: packages/openapi-2-kong/tsconfig.build.json [hunk 6]
```diff
@@ -5,7 +5,7 @@
     "outDir": "dist",
     "rootDir": "src",
     "resolveJsonModule": true,
-    "strict": false
+    "strict": true
```
Comment (develohpanda) [inline packages/openapi-2-kong/tsconfig.build.json:8]: :tada:

**Review by develohpanda — APPROVED** [review]
Didn't happen before but thoughts on keeping one set of input fixtures, but testing both dc and k8s generation with them? The same input _should_ run with both, so it makes sense to me to share the input fixtures.

File: packages/openapi-2-kong/src/types/kubernetes-config.ts (hunk 2 above)
Comment (dimitropoulos) [reply packages/openapi-2-kong/src/types/kubernetes-config.ts:78]: it's better than nothing - worth having, imo: 576469593c44ea5ccd5abbc7d437eae9df2c5bc1

File: packages/openapi-2-kong/src/kubernetes/plugin-helpers.ts (hunk 3 above)
Comment (dimitropoulos) [reply packages/openapi-2-kong/src/kubernetes/plugin-helpers.ts:61]: yeah, it's a 4.1 feature, so I think people are just now starting to see the use for it.  This is, actually, probably the most appropriate use of it I've yet seen.  It was done by anders himself https://github.com/microsoft/TypeScript/pull/40336 and there are 4 of them at this moment: https://www.typescriptlang.org/docs/handbook/2/template-literal-types.html#intrinsic-string-manipulation-types in TypeScript itself, although, as you might have predicted, there are another 19 that type-fest practically immediately added: https://github.com/sindresorhus/type-fest#template-literal-types

My favorite is 
> Get - Get a deeply-nested property from an object using a key path, like Lodash's .get() function.
> - https://github.com/sindresorhus/type-fest/blob/main/ts41/get.d.ts

Kinda crazy that you can do this with just the type system.

File: packages/openapi-2-kong/src/declarative-config/plugins.ts (hunk 4 above)
Comment (dimitropoulos) [reply packages/openapi-2-kong/src/declarative-config/plugins.ts:110]: I'd like to follow up on this.  The ultimate problem was this signature

```ts
export function generateOperationPlugins(
  operation: OA3Operation,
  pathPlugins: DCPlugin[],
  parentValidatorPlugin?: Record<string, any> | null,
  tags?: string[],
)
```
TypeScript will not allow a non-optional argument (`tags`) to follow an optional one (`parentValidatorPlugin`).  This is another reason why the "option bag" approach is superior, is you can make any of them optional at any time without having to worry about breaking any API somewhere.

I'll submit a PR for this immediately after merging this one.

File: packages/openapi-2-kong/src/types/declarative-config.ts (hunk 5 above)
Comment (dimitropoulos) [reply packages/openapi-2-kong/src/types/declarative-config.ts:13]: I'd definitely like to understand this more, for sure.  It was added because as far as I can tell, from looking at the tests, it's valid: 

image

I'll definitely look to this as the next main area to sure up.

File: packages/openapi-2-kong/src/declarative-config/plugins.ts (hunk 4 above)
Comment (dimitropoulos) [reply packages/openapi-2-kong/src/declarative-config/plugins.ts:110]: https://github.com/Kong/insomnia/pull/3416

Comment (develohpanda) [reply packages/openapi-2-kong/src/declarative-config/plugins.ts:110]: Yah I agree with the option bag approach too 🎉
