### PR TITLE
fix #5976: set content-type on openapi3 imports

### LINKED ISSUE #5976: Importing an OpenAPI v3 spec does not set Content-Type for json requests
### Expected Behavior

It should automatically detect content-type from the request media type when importing from an OpenAPI v3 spec.

### Actual Behavior

`Content-Type: application/json` header is not being added for json requests in an OpenAPI v3 spec.

Need to manually switch it to another media type and switch it back to json for the header to be applied.

### Reproduction Steps

1. Import an openapi v3 spec with a json request
2. Make a request (no `Content-Type: application/json` header)
3. Switch to some other content type and switch back to json
4. Make a request (`Content-Type: application/json` header is added now)

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

_No response_

### Insomnia Version

2023.2.2

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 20.04.5 LTS

### Installation method

insomnia.rest

### Last Known Working Insomnia version

_No response_

### PR DESCRIPTION
**Pull request by filfreire**
Closes #5976 

Related to similar past change - https://github.com/Kong/insomnia/pull/5812

If mime type is set for bodies in the OpenAPI imported spec, we now set the content-type on the generated requests as well.

changelog(Fixes): Added a fix to help set Content-Type header when importing requests from OpenAPI 3 specs of which the mime-type was already specified

### CODE REVIEW

File: packages/insomnia/src/utils/importers/importers/openapi-3.ts [hunk 1]
```diff
@@ -287,7 +287,24 @@ const importRequest = (
...
+    paramHeaders = [
+      {
+        name: 'Content-Type',
+        disabled: false,
+        // @ts-expect-error -- ??
+        value: body.mimeType,
+      },
+      ...paramHeaders,
+    ];
+  }
```
Comment (jackkav) [inline packages/insomnia/src/utils/importers/importers/openapi-3.ts]: since it doesn't appear to mutate the body, would it make sense for this logic to belong inside `prepareHeaders()`?

Comment (filfreire) [reply packages/insomnia/src/utils/importers/importers/openapi-3.ts]: sounds good to me - moved it inside to `prepareHeaders` 👍

**Review by jackkav — APPROVED** [review]
