### PR TITLE
Git clone fails on Windows. This fixes it.

### LINKED ISSUE #2153: Git Sync clone not working on Windows
**Describe the bug**
When pulling documents using Git Sync a `Error: ENOENT: no such file or directory` error is reported and nothing is updated. This appears to occur on Windows and not OS X.

**To Reproduce**
Quick steps:
1. Create -> Git Clone
2. Paste `https://github.com/bagf/pullcrash.git` into 'Git URI' field
3. Enter your author name and email 
4. Paste authentication token
5. Done

1. Create a 'Blank Document' called 'pullcrash'
2. Open pullcrash and go to debug
3. Create a new request 'My Request'
4. Click 'Setup Git Sync' -> Repository Settings
5. Paste in working Authentication Token, Git URI, Author name and email
6. Click Done
7. Click 'master' to bring up Git Sync menu
8. Click commit
9. Enter 'Testing' as the description and tick all 'Unversioned Objects'
10. Click Commit
11. Open Git Sync menu and Click push
12. Go back to 'Documents' screen and delete the pullcrash document
13. Create using 'Git clone'
14. Paste same details from step 5
15. Click Done

**Expected behavior**
The repository settings modal closes and my pullcrash document is promoted to be imported after cloning the pullcrash Git repository.

**Screenshots**
Committing all objects:
tickall

Console log:
console

**Desktop (please complete the following information):**
 - OS: Windows 10 Version 1909 (OS Build 18363.815)
 - Installation Method: Git Release .exe
 - App Version v2020.1.3

**Additional context**
I don't know if it matters that much but i'm using Git 2.26.2-windows.1 locally and I **do not** have node js installed.

It seems committing and pushing works fine, but pulling results in:
```
bundle.js:250449 Uncaught (in promise) Error: ENOENT: no such file or directory, scandir '\\.insomnia\ApiSpec\'
    at MemPlugin._assertExists (bundle.js:250449)
    at MemPlugin._assertDir (bundle.js:250474)
    at MemPlugin.mkdir (bundle.js:250317)
    at FileSystem.mkdir (C:\Users\rory9\AppData\Local\insomnia-designer\app-2020.1.3\resources\app.asar\node_modules\isomorphic-git\dist\for-node\isomorphic-git\index.js:391)
    at FileSystem.mkdir (C:\Users\rory9\AppData\Local\insomnia-designer\app-2020.1.3\resources\app.asar\node_modules\isomorphic-git\dist\for-node\isomorphic-git\index.js:407)
```

### PR DESCRIPTION
**Pull request by develohpanda**
This approach sets `.` as the base directory, instead of `/`. Windows cannot handle the double slash route (eg `//.insomnia/ApiSpec/`) that gets created by using `/` as the base dir, but both Windows and macOS handle `./.insomnia/ApiSpec/` just fine. 

This is because a path starting with a double-slash, on Windows, is a network path. As a result, the `path.dirname` function does not return the data expected by our code. Further notes in the linked issue. Closes #2153 

The breaking test for the exact case in the initial report on Windows is as follows. The test succeeds on macOS (posix) but fails on Windows (win32), with `GIT_CLONE_DIR = '/'`.

image

With `GIT_CLONE_DIR = '.'` as this PR sets, this test is fixed.

### CODE REVIEW

**Comment by develohpanda** [comment]
Sigh; I'm working through commit logic not working correctly on Windows, and it seems `isomorphic-git` has hard-coded the usage of the `posix` separator (`/`) - https://github.com/isomorphic-git/isomorphic-git/blob/c2cd5cb8c4f69163de535e026f9e6e09cef29dc6/src/api/status.js#L172.

This logic is used when getting git status. ~Reverted this back to draft to figure out any implications on this PR~ Shouldn't be any.

File: packages/insomnia-app/app/sync/git/__mocks__/path.js [hunk 1]
```diff
@@ -0,0 +1,12 @@
...
+
+const exportObj = { __mockPath, ...path };
+
+function __mockPath(type) {
+  const mock = type === 'win32' ? path.win32 : path.posix;
+
+  Object.keys(mock).forEach(k => (exportObj[k] = mock[k]));
+}
+
+module.exports = exportObj;
```
Comment (gschier) [inline packages/insomnia-app/app/sync/git/__mocks__/path.js:12]: Woah, very nice! Was there a technical reason for not using ES6-style import/exports here?

File: packages/insomnia-app/app/sync/git/__tests__/git-vcs.test.js [hunk 2]
```diff
@@ -1,16 +1,20 @@
-import GitVCS, { GIT_NAMESPACE_DIR } from '../git-vcs';
+import GitVCS, { GIT_CLONE_DIR, GIT_INSOMNIA_DIR } from '../git-vcs';
 import { setupDateMocks } from './util';
 import { MemPlugin } from '../mem-plugin';
+import path from 'path';
+jest.mock('path');
 
-describe('Git-VCS', () => {
+describe.each(['win32', 'posix'])('Git-VCS using path.%s', type => {
```
Comment (gschier) [inline packages/insomnia-app/app/sync/git/__tests__/git-vcs.test.js:7]: Dang, I didn't even know `describe.each` existed 😃

File: packages/insomnia-app/app/sync/git/ne-db-plugin.js [hunk 3]
```diff
@@ -4,16 +4,19 @@ import * as db from '../../common/database';
...
 export default class NeDBPlugin {
   _workspaceId: string;
+  _cloneDirRegExp: RegExp;
 
   constructor(workspaceId: string) {
     if (!workspaceId) {
       throw new Error('Cannot use NeDBPlugin without workspace ID');
     }
     this._workspaceId = workspaceId;
+    const pathSep = path.sep === path.win32.sep ? '\\\\' : '/';
```
Comment (gschier) [inline packages/insomnia-app/app/sync/git/ne-db-plugin.js:20]: Should we comment what we're doing here?

Comment (gschier) [reply packages/insomnia-app/app/sync/git/ne-db-plugin.js:20]: Also, took me a while to understand why it was 4 backslashes instead of 2. Is it because we have to escape the JS string, then also the RegExp? `\\\\` > `\\` > `\`

File: packages/insomnia-app/app/sync/git/ne-db-plugin.js [hunk 4]
```diff
@@ -201,7 +204,12 @@ export default class NeDBPlugin {
   _parsePath(filePath: string): { root: string | null, type: string | null, id: string | null } {
     filePath = path.normalize(filePath);
 
-    const [root, type, idRaw] = filePath.split(path.sep).filter(s => s !== '');
+    // FilePath will start with the clone directory. We want to remove the clone dir, so that the
+    // segments can be extracted correctly.
+    filePath = filePath.replace(this._cloneDirRegExp, '');
```
Comment (gschier) [inline packages/insomnia-app/app/sync/git/ne-db-plugin.js:211]: Nice, this seems like a great place for this.

File: packages/insomnia-app/app/ui/components/modals/git-repository-settings-modal.js [hunk 5]
```diff
@@ -110,10 +110,9 @@ class GitRepositorySettingsModal extends React.PureComponent<Props, State> {
     const inputs = {};
 
     if (gitRepository) {
-      const creds = gitRepository.credentials || {};
-      inputs.token = typeof creds.token === 'string' ? creds.token : '';
```
Comment (gschier) [inline packages/insomnia-app/app/ui/components/modals/git-repository-settings-modal.js:114]: Was token removed here on purpose?

File: packages/insomnia-app/app/ui/components/wrapper-home.js [hunk 6]
```diff
@@ -219,14 +224,16 @@ class WrapperHome extends React.PureComponent<Props, State> {
 
           // Import all docs to the DB
           onConfirm: async () => {
-            const { handleSetActiveWorkspace } = this.props;
+            const {
+              wrapperProps: { handleSetActiveWorkspace },
+            } = this.props;
```
Comment (gschier) [inline packages/insomnia-app/app/ui/components/wrapper-home.js:229]: Nice catch

**Review by gschier — CHANGES_REQUESTED** [review]
Looks good! A few comments but all minor 😄

File: packages/insomnia-app/app/sync/git/__mocks__/path.js (hunk 1 above)
Comment (develohpanda) [reply packages/insomnia-app/app/sync/git/__mocks__/path.js:12]: If you try to import the module being mocked (importing `path` in `__mocks__/path.js`), then jest gets stuck in an infinite loop. Using `jest.requireActual` bypasses that.

The export is tricky... The test setup logic (to prepare the database) calls into `mkdirp`, which uses a CommonJS import (`require('path')`) and it fails to import `path` module correctly if the mock is setup with es6-style exports.

image

In all the testing I've done with mocks, I've never been able to get ES6-style mocks working properly, and most of the examples use `module.exports` so haven't given too much more thought into this since the first time I ached over it 😅 If you have any other ideas on how to get across that, that'd be super useful!

File: packages/insomnia-app/app/sync/git/ne-db-plugin.js (hunk 4 above)
Comment (develohpanda) [reply packages/insomnia-app/app/sync/git/ne-db-plugin.js:211]: It _is_ trivial given what `cloneDir` is set to, but following the general pattern in the rest of this PR to remove all hard-coding to do with file-paths in git (and be independent of what `cloneDir` is set to), I thought this solution would be more stable.

File: packages/insomnia-app/app/sync/git/ne-db-plugin.js (hunk 3 above)
Comment (develohpanda) [reply packages/insomnia-app/app/sync/git/ne-db-plugin.js:20]: Added a comment to explain this. It _is_ to escape both the JS string and RegExp. 👍

**Review by gschier — APPROVED** [review]
Happy to finally get this fix in!
