### PR TITLE
UI improvements - Debug Sidebar - drag and drop sort and filter

### LINKED ISSUE #6288: Requests cannot be filtered
### Expected Behavior

When typing something into the Filter text box above the request list, the visible requests should be filtered by the entered text.

### Actual Behavior

The request list is not filtered by the entered text.

### Reproduction Steps

1. Go to a collection of requests
2. Type something into the Filter text box above the request list.
3. The displayed requests are not filtered by the entered text.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

_No response_

### Insomnia Version

2023.5.1

### What operating system are you using?

Windows

### Operating System Version

Windows 11 version 22H2, macOS 13.5

### Installation method

Downloaded from insomnia.net

### Last Known Working Insomnia version

_No response_

### PR DESCRIPTION
**Pull request by gatzjames**
fixes: #6288 #6284 #6335 #6202 #6278 #6349 (so many duplicate issues)

todo
- [x] drag and drop
- [x] sort
- [x] filter
- [x] multiple folder test
- [x] colors and methods
- [x] pin/unpin
- [x] context menus
- [x] clean up tree traversal

### scoped out
- filter reset on create
- type request operation update
- double click rename (needs ux pass)
- request tree collection in export requests modal could use a similar approach
- right click context
- colors, env dropdown and method tags
- indentation on pinned requests

### CODE REVIEW

File: packages/insomnia/src/ui/routes/actions.tsx [hunk 1]
```diff
@@ -932,3 +936,64 @@ export const updateSettingsAction: ActionFunction = async ({ request }) => {
...
+  let item;
+  if (isRequestGroupId(id)) {
+    item = await models.requestGroup.getById(id);
+  } else if (isRequestId(id)) {
+    item = await models.request.getById(id);
+  } else if (isWebSocketRequestId(id)) {
+    item = await models.webSocketRequest.getById(id);
+  } else if (isGrpcRequestId(id)) {
+    item = await models.grpcRequest.getById(id);
+  }
```
Comment (jackkav) [inline packages/insomnia/src/ui/routes/actions.tsx]: we have something like this in requestOperations

File: packages/insomnia/src/ui/routes/actions.tsx [hunk 2]
```diff
@@ -932,3 +936,64 @@ export const updateSettingsAction: ActionFunction = async ({ request }) => {
...
+  if (id === targetId) {
+    return null;
+  }
+
+  const item = await getCollectionItem(id);
+  const targetItem = await getCollectionItem(targetId);
+
+  // @TODO METASortKEY
+  if (!isRequestGroup(targetItem)) {
+    console.log('Moving to request');
```
Comment (jackkav) [inline packages/insomnia/src/ui/routes/actions.tsx]: can remove todo and console log

File: packages/insomnia/src/ui/routes/actions.tsx [hunk 3]
```diff
@@ -932,3 +936,64 @@ export const updateSettingsAction: ActionFunction = async ({ request }) => {
...
+        await update(item, { parentId: targetItem.parentId, metaSortKey });
+      }
+    } else {
+      if (isRequestGroup(item)) {
+        await models.requestGroup.update(item, { parentId: targetItem._id, metaSortKey });
+      } else {
+        await update(item, { parentId: targetItem._id, metaSortKey });
+      }
+    }
+  }
```
Comment (jackkav) [inline packages/insomnia/src/ui/routes/actions.tsx]: return early eliminate elses and nested ifs

File: packages/insomnia/src/ui/routes/workspace.tsx [hunk 4]
```diff
@@ -73,67 +103,177 @@ export const workspaceLoader: LoaderFunction = async ({
...
+    | ApiSpec
+    | Request
+    | WebSocketRequest
+    | GrpcRequest
+    | RequestGroup
+  )[] = [];
   syncItemsList.push(activeWorkspace);
   syncItemsList.push(baseEnvironment);
-  subEnvironments.forEach(e => syncItemsList.push(e));
+  subEnvironments.forEach((e) => syncItemsList.push(e));
```
Comment (jackkav) [inline packages/insomnia/src/ui/routes/workspace.tsx]: bugfix?

File: packages/insomnia/src/ui/routes/workspace.tsx [hunk 5]
```diff
@@ -150,6 +290,7 @@ export const workspaceLoader: LoaderFunction = async ({
     requestTree,
     grpcRequests,
     syncItems,
+    collection: buildCollection(),
```
Comment (jackkav) [inline packages/insomnia/src/ui/routes/workspace.tsx]: rename requestTree and collection to collectionTree and collectionList?

File: packages/insomnia/src/ui/routes/workspace.tsx [hunk 6]
```diff
@@ -73,67 +103,177 @@ export const workspaceLoader: LoaderFunction = async ({
...
+          level,
+          pinned: node.pinned,
+          parentId: node.doc.parentId,
+          tag,
+          type: 'request',
+          id: node.doc._id,
+        });
+      }
+    };
+    tree.forEach((node) => build(node, 0));
```
Comment (jackkav) [inline packages/insomnia/src/ui/routes/workspace.tsx]: rewrite this as a map

File: packages/insomnia/src/ui/routes/debug.tsx [hunk 7]
```diff
@@ -99,17 +158,20 @@ export const Debug: FC = () => {
...
     });
   }, []);
 
-  const {
-    settings,
-  } = useRouteLoaderData('root') as RootLoaderData;
-  const { sidebarFilter } = activeWorkspaceMeta;
-  const [runningRequests, setRunningRequests] = useState<Record<string, boolean>>({});
+  const { settings } = useRouteLoaderData('root') as RootLoaderData;
+  // const { sidebarFilter } = activeWorkspaceMeta;
```
Comment (jackkav) [inline packages/insomnia/src/ui/routes/debug.tsx]: you ran an onconventional autoformat on this file, which made finding this commented out line more challenging than it had to be as a reviewer.

File: packages/insomnia/src/ui/index.tsx [hunk 8]
```diff
@@ -54,7 +54,8 @@ const router = createMemoryRouter(
     {
       path: '/',
       id: 'root',
-      loader: async (...args) => (await import('./routes/root')).loader(...args),
+      loader: async (...args) =>
```
Comment (jackkav) [inline packages/insomnia/src/ui/index.tsx:57]: I can't review this file because theres too much unconventional autoformat

File: packages/insomnia/src/ui/routes/actions.tsx (hunk 1 above)
Comment (jackkav) [reply packages/insomnia/src/ui/routes/actions.tsx]: on second thought we could add request groups into these helpers

**Review by jackkav — APPROVED** [review]

**Review by filfreire — APPROVED** [review]

**Comment by marchpane** [comment]
Just fyi: This PR does not solve the following issues:

- https://github.com/Kong/insomnia/issues/6284
- https://github.com/Kong/insomnia/issues/6288

**Comment by jackkav** [comment]
@marchpane Please be patient we are preparing the release and it will be available in the next 24 hours.
