### PR TITLE
fix: oauth2 inheritance [INS-5023]

### LINKED ISSUE #7508: OAuth 2.0 authentication issues in 9.2.0 version
### Expected Behavior

Should be able to fetch access token or refresh access token with Oath 2.0 authentication.

### Actual Behavior

Failed to fetch token url status=0. no description provided

### Reproduction Steps

1. create a GET request
2. Set the AUTH type to Oath 2.0 and grant type to client credentials
3. set access token url, client ID and client secret

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

_No response_

### Insomnia Version

9.2.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Enterprise

### Installation method

.exe file from website

### Last Known Working Insomnia version

NA

### LINKED ISSUE #7880: Requests don't pick up new OAuth 2.0 token
### Expected Behavior

That if I generate a new token, all child requests will use new token.

### Actual Behavior

When I change environment, I clear the token, generate a new one and it still uses the old token meant for a different environment. 

### Reproduction Steps

1. Create a folder with `OAuth 2.0` auth
2. create a child request with `Inherit from parent` auth
3. generate a new OAuth 2.0 token in folder
4. send child request
5. change environment
6. clear token
7. generate new token
8. send child request again
9. seems like child request is using the token of old env instead of using the new generated token

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

it seems that if I duplicate the request and the duplication uses the new token

### Insomnia Version

9.3.3

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu Cinnamon noble 24.04 x86_64

### Installation method

AppImage

### Last Known Working Insomnia version

_No response_

### LINKED ISSUE #8374: Requests use stale OAuth 2.0 Token after clearing OAuth 2 session
### Expected Behavior

If I change accounts when using OAuth 2.0 authentication, I expect all of the requests in that folder to use the new account. But unfortunately, requests use the stale (previous) OAuth 2.0 Token after clearing OAuth 2 session and clearing and retrieving a new token with a different account. 

### Actual Behavior

I am using Insomnia in scratch pad mode. I have a folder set up with OAuth 2.0 authentication. The requests inside the folder are set to inherit auth from parent. Unfortunately, when the parent folder has a new account authenticated, the underlying requests never use the new account. 

I've tried "Clear OAuth 2 session" as well as "Clear" and "Refresh Token" on the OAuth 2 tab. I've also tried all of these after rebooting the application. The requests will continue to use the old account even though the new JWT access token on the OAuth 2 tab on the folder clearly shows that new account that it should be using. 

### Reproduction Steps

1. In Scratch Pad mode, create a folder with OAuth 2.0 authentication with at least one request in it. 
2. Authenticate with an account and run your request, checking that the account is the correct one. 
3. Go back and login with a different account at the folder level. 
4. You should see that you request will never use the new account. 

### Is there an existing issue for this?

- [x] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Which sync method do you use?

- [ ] Git sync.
- [ ] Insomnia Cloud sync.
- [x] Local only

### Additional Information

_No response_

### Insomnia Version

10.3.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Enterprise Version 22H2 OS build 19045.5371

### Installation method

corporate install

### Last Known Working Insomnia version

_No response_

### PR DESCRIPTION
**Pull request by ryan-willis**
fixes #7508 
fixes #7880 
fixes #8374

~~This change alters the authentication model for OAuth2 requests to add an additional optional field that is derived at request time and used to inherit the correct token when executing a request from within a folder that has OAuth2 configured.~~

EDIT: This change alters the RenderedRequest type to include an `_authParentId` field that is used to determine what `parentId` to use when storing/retrieving an OAuth2 token.

The smoke test has been updated with the reproduction steps from the linked issues to confirm that it uses the "nearest" folder's token every attempt, so instead of storing a token with a relationship to the request itself, it maintains the relationship to the folder.

### CODE REVIEW

**Review by marckong — DISMISSED** [review]
Simple and to the point PR!

File: packages/insomnia/src/models/request.ts [hunk 1]
```diff
@@ -82,6 +82,8 @@ export interface AuthTypeOAuth2 {
   pkceMethod?: string;
   responseType?: OAuth2ResponseType;
   origin?: string;
+  // to identify stored token inheritance from a RequestGroup (if applicable)
+  parentId?: string;
```
Comment (jackkav) [inline packages/insomnia/src/models/request.ts]: what are the consequences of creating a relationship like this?

Comment (marckong) [reply packages/insomnia/src/models/request.ts]: hm good question. I was looking through the code and we are just doing getOrCreateByParentId. It just reads an entity. Only if there is none, then it creates, which I think happens regardless of this change. I can't think of any concerning consequence from this change.

Comment (ryan-willis) [reply packages/insomnia/src/models/request.ts]: The only thing that comes to mind is how differently we handle folder deletes vs request deletes, and the delete folder code might not look for token entities, leaving them dangling. I'll take a look to see

EDIT: looks like we're clear on that front, any time anything is removed we gather descendants and remove those too

Comment (jackkav) [reply packages/insomnia/src/models/request.ts]: hmm, I think. we have a database normalisation problem there.
Our database uses parentIds explicitly for joining different objects. There should never be an object with two parentIds. Because the withDescendents code could not compute children if it needs to search every object within the db objects.

This authentication object is a property of request. therefore.
```
request:{
  parentId:'afolder?',
  authentication:{
    parentId:'somethingelse?'
  }
}
```
it now becomes possible for a request to have a parentId and a authentication object to have a different parentId.

I would suggest two direction this PR could take:

1. split and migrate request.authentication into a new db object with a parentIds or request or folder.
2. improve the code which requires this parentId, to avoid it.

Comment (ryan-willis) [reply packages/insomnia/src/models/request.ts]: Ah, I see. The authentication object should only have that field on it during a request, and not make it to the db, but if it's doing that, I'm leaning toward option 2 and wrapping that up into a
```
{
  requestOrGroupId: "parentId",
  authentication: original
}
```
for the OAuth paths, what do you think?

Comment (marckong) [reply packages/insomnia/src/models/request.ts]: @jackkav's concerns are valid. I think 1 might be a better option but would require migration path for previous versions. Option 2 would be a good alternative without the db migration path. I didn't quite understand the 2 option @ryan-willis you are proposing. Could you help me understand?

Comment (ryan-willis) [reply packages/insomnia/src/models/request.ts]: I'm thinking of changing interface for these methods, rather than the models, let me draft a change that targets this branch that will explain it better

Comment (ryan-willis) [reply packages/insomnia/src/models/request.ts]: I've confirmed that this field doesn't persist on the request's authentication object, and is only utilized in the active context of a request action.

I can rename this field to make it less conflating, something like `sourceId` or `requestOrGroupId` (since we use that for the same purpose) if that's preferred

Comment (jackkav) [reply packages/insomnia/src/models/request.ts]: so the auth object is updated for the purpose of something that happens later on, but not persisted in the database, in which case the db object shouldnt be modified at all, perhaps create a new code only object. Let's discuss on zoom since I build the first version I might have some insights that are hard to recall in a PR review.

Comment (ryan-willis) [reply packages/insomnia/src/models/request.ts]: @jackkav that's what I was leaning toward with option 2, I'll update this PR with that

**Review by jackkav — COMMENTED** [review]
Some things come to mind here
- This e2e test and implemenation decision here would be much clearer if we add a UX to view oauth2 tokens, even just a tooltip
- the naming closestAuthId would be clearer than authParentId since its not a direct parent in the same sense its used in the db model, but a indirect relationship does exist.
- An alternative implementation could be re-running the closest auth algorithm to get the id in `getExistingAccessTokenAndRefreshIfExpired` every time instead of storing the closest auth id and carrying it around.

This one hurts the brain a bit

**Review by jackkav — APPROVED** [review]
would prefer a stateless approach but happy to move it forward now the naming is clarified, would be great to plan some improvements to this feature too
