### PR TITLE
fixes CodeMirror opacity for disabled (or not) GraphQL body text

### LINKED ISSUE #4181: GraphQL Query/Mutation syntax highlight partially has less opacity
### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for a bug that matches the one I want to file, without success.

### Insomnia Version

2021.6.0

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey 12.0.1

### Installation method

download from insomnia.rest

### Last Known Working Insomnia version

2021.4.0

### Expected Behavior

It should have full opacity like this

image

### Actual Behavior

Some parts of the GraphQL code has less alpha that the rest

image

### Reproduction Steps

1. Create a new Request
2. Switch to GraphQL
3. Put this in the request body

```gql
{
  wishlists:paginateWishlists {
    totalCount
    hasNextPage
      nodes {
      _id
      title
      items {
        __typename
        ...WishlistPlace
        ...WishlistArticle
        ...WishlistVideo
        ...WishlistProduct
      }
    }
  }
}


fragment WishlistPlace on PlacePayload {
  _id
  name
}

fragment WishlistArticle on ArticlePayload {
  _id
 
  thumbnailUrl
}


fragment WishlistVideo on VideoPayload {
  _id
}

fragment WishlistProduct on ProductPayload {
  _id
  
}
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by dimitropoulos**
closes: INS-1157
closes: https://github.com/Kong/insomnia/issues/4181

https://user-images.githubusercontent.com/15232461/140808850-fb83e521-785a-4538-89c4-f026d0a6a6ba.mp4

### CODE REVIEW

File: packages/insomnia-app/app/ui/components/editors/body/graph-ql-editor.tsx [hunk 1]
```diff
@@ -216,32 +230,24 @@ export class GraphQLEditor extends PureComponent<Props, State> {
...
-      const from = {
-        line: startToken.line - 1,
-        ch: startToken.column - 1,
-      };
-      const to = {
-        line: endToken.line,
-        ch: endToken.column - 1,
-      };
+      .filter(complement(matchesOperation(operationName)))
+      .filter(hasLocation)
```
Comment (develohpanda) [inline packages/insomnia-app/app/ui/components/editors/body/graph-ql-editor.tsx:236]: Two ramda specific questions:
- Looking at the [docs](https://ramdajs.com/docs/#complement), it appears that `not` does something similar: why did you choose `complement` in particular?
- Is it possible to combine the three filters into one using ramda, so that we run one filter, then one map?

**Review by develohpanda — APPROVED** [review]
LGTM, nice fix 🚀 

https://www.loom.com/share/8b4330f7a4a74f22a2fecab4f375edaa

File: packages/insomnia-app/app/ui/components/editors/body/graph-ql-editor.tsx (hunk 1 above)
Comment (dimitropoulos) [reply packages/insomnia-app/app/ui/components/editors/body/graph-ql-editor.tsx:236]: > Looking at the docs, it appears that not does something similar: why did you choose complement in particular?

`not` is for literals (e.g. `true`) and `complement` is for functions (e.g. `() => true`).

> Is it possible to combine the three filters into one using ramda, so that we run one filter, then one map?

Definitely!  In this PR I was trying as hard as possible to not introduce ramda since this is (ideally) as close to a revert as possible and adding ramda adds new surface area, despite my undying love for it, haha.

To start, we could remove the three filters with `allPass`:

```ts
    this._disabledOperationMarkers = pipe(
      () => _documentAST.definitions,
      filter(allPass([
        isOperationDefinition,
        complement(matchesOperation(operationName)),
        hasLocation,
      ])),
      map(({ loc: { startToken, endToken } }) => {
        const from = {
          line: startToken.line - 1,
          ch: startToken.column - 1,
        };
        const to = {
          line: endToken.line,
          ch: endToken.column - 1,
        };

        return _queryEditor.getDoc().markText(from, to, {
          className: 'cm-gql-disabled',
        });
      }),
    )();
 ```

And if we wanted to remove the second loop through with the map we can just reduce:

```ts
    this._disabledOperationMarkers = reduce((accumulator, definition) => {
      if (!allPass([
        isOperationDefinition,
        complement(matchesOperation(operationName)),
        hasLocation,
      ])(definition)) {
        return accumulator;
      }

      const { loc: { startToken, endToken } } = definition;

      const from = {
        line: startToken.line - 1,
        ch: startToken.column - 1,
      };
      const to = {
        line: endToken.line,
        ch: endToken.column - 1,
      };

      const operation = _queryEditor.getDoc().markText(from, to, {
        className: 'cm-gql-disabled',
      });

      return [
        ...accumulator,
        operation,
      ];
    }, [], _documentAST.definitions);
```

___

Also, if I were using `pipe` normally here, I'd just do `reject` rather than `filter`+`complement` but since we were using builtin array methods I didn't want to change that in the context of a revert like this PR, so I left it.

Comment (develohpanda) [reply packages/insomnia-app/app/ui/components/editors/body/graph-ql-editor.tsx:236]: Nice! Very useful, thanks for noting all this down
