### PR TITLE
fix: duplicate methods from gRPC reflection

### LINKED ISSUE #5891: Insomnia shows duplicated options in gRPC method dropdown menu
### Expected Behavior

- The gRPC method dropdown menu shows one option per method.

### Actual Behavior

- The gRPC method dropdown menu shows duplicated options.

**Gif animation**
InsomniaDuplicatedGrpcMethods

**Screenshot**
image

### Reproduction Steps

1. Run `docker pull tkpd/gripmock:v1.11-beta` to pull gRPC mock server docker image.
2. Create a `service.proto` file with the following contents.

```proto
syntax = "proto3";

message FooRequest {
    string foo = 1;
}

message FooResponse {
    string foo = 1;
}

message BarRequest {
    string bar = 1;
}

message BarResponse {
    string bar = 1;
}

service FooService {
    rpc Foo (FooRequest) returns (FooResponse);
}

service BarService {
    rpc Bar (BarRequest) returns (BarResponse);
}
```

4. Go to the directory where the `service.proto` file is located and run the following command to spin up the gRPC server. 

```bash
docker run --rm -p 4770:4770 \
    -v ${PWD}/service.proto:/proto/service.proto \
    tkpd/gripmock:v1.11-beta /proto/service.proto
```

5. Open Insomnia and create a new gRPC request with the host set to `localhost:4770`.
6. Click on the refresh button to use server reflection.
7. Click on "Select Method" to open the dropdown menu.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

It appears as if Insomnia duplicates all methods for every gRPC service after the first one. That is:

- proto file with one service declaration: everything ok
- proto file with two service declarations: gRPC methods duplicated once
- proto file with three service declarations: gRPC methods duplicated twice

### Insomnia Version

2023.1.0

### What operating system are you using?

macOS

### Operating System Version

Ventura 13.2.1

### Installation method

insomnia.rest

### Last Known Working Insomnia version

_No response_

### PR DESCRIPTION
**Pull request by nbgraham**
Closes #5891 

When getting the available gRPC methods through server reflection, the code checks service by service.
However, for each service, it was grabbing _all_ the methods in the file that the service was defined, so if multiple services were defined in one file, it would duplicate those methods.
I updated the code to only retrieve the methods applicable to each service to avoid duplicate methods.

### CODE REVIEW

File: packages/insomnia/src/main/ipc/grpc.ts [hunk 1]
```diff
@@ -317,4 +319,8 @@ const filterDisabledMetaData = (metadata: GrpcRequestHeader[],): Metadata => {
 export type GrpcMethodType = 'unary' | 'server' | 'client' | 'bidi';
 const closeAll = (): void => grpcCalls.forEach(x => x.cancel());
 
-electron.app.on('window-all-closed', closeAll);
+if (typeof electron.app.on === 'function') {
+  electron.app.on('window-all-closed', closeAll);
+} else {
+  console.warn('electron.app.on is not a function. Are you running a test?');
+}
```
Comment (nbgraham) [inline packages/insomnia/src/main/ipc/grpc.ts:343]: this line was failing any tests since `electron` was not configured in the test environment. 
I think a better solution would be to pull out all "pure" code into its own separate file and only import that in the tests, but I didn't want to create a giant git diff or risk breaking other imports.

File: packages/insomnia/src/main/ipc/grpc.ts [hunk 2]
```diff
@@ -105,7 +108,7 @@ const getMethodsFromReflection = async (host: string, metadata: GrpcRequestHeade
     throw error;
   }
 };
-const loadMethodsFromReflection = async (options: { url: string; metadata: GrpcRequestHeader[] }): Promise<GrpcMethodInfo[]> => {
+export const loadMethodsFromReflection = async (options: { url: string; metadata: GrpcRequestHeader[] }): Promise<GrpcMethodInfo[]> => {
```
Comment (nbgraham) [inline packages/insomnia/src/main/ipc/grpc.ts:111]: needed to import in unit test

File: packages/insomnia/src/main/ipc/grpc.ts [hunk 3]
```diff
@@ -145,10 +148,26 @@ export const getSelectedMethod = async (request: GrpcRequest): Promise<MethodDef
 };
 export const getMethodsFromPackageDefinition = (packageDefinition: PackageDefinition): MethodDefs[] => {
   return Object.values(packageDefinition)
-    .filter((obj: AnyDefinition): obj is EnumTypeDefinition | MessageTypeDefinition => !obj.format)
+    .filter(isServiceDefinition)
```
Comment (nbgraham) [inline packages/insomnia/src/main/ipc/grpc.ts:151]: This TS assertion was backwards. Both `EnumTypeDefinition` and `MessageTypeDefinition ` have a string `format` property, but the `ServiceDefinition` does not.

File: packages/insomnia/src/main/ipc/__tests__/grpc.test.ts [hunk 4]
```diff
@@ -0,0 +1,133 @@
...
+            message FooRequest {
+                string foo = 1;
+            }
+
+            message FooResponse {
+                string foo = 1;
+            }
+
+            service FooService {
+                rpc format (FooRequest) returns (FooResponse);
```
Comment (nbgraham) [inline packages/insomnia/src/main/ipc/__tests__/grpc.test.ts:67]: Before, an rpc with name `format` was mistakenly excluded as a `MessageTypeDefinition` or `EnumTypeDefinition`

File: packages/insomnia/src/main/ipc/__tests__/grpc.test.ts [hunk 5]
```diff
@@ -0,0 +1,133 @@
...
+
+    it('parses methods', async () => {
+      const methods = await loadMethodsFromReflection({ url: 'foo-bar.com', metadata: [] });
+      expect(methods).toStrictEqual([{
+        type: 'unary',
+        fullPath: '/FooService/Foo',
+      }, {
+        type: 'unary',
+        fullPath: '/BarService/Bar',
+      }]);
```
Comment (nbgraham) [inline packages/insomnia/src/main/ipc/__tests__/grpc.test.ts:129]: Before, this test fails by duplicating each of these methods

**Review by gatzjames — APPROVED** [review]

**Comment by jackkav** [comment]
Brilliant contribution and bug report @nbgraham @Tomasito665
If the CI passes this is good to go in

**Comment by filfreire** [comment]
@nbgraham you can claim a free tshirt for this PR contribution - find more at https://konghq.com/community/open-source-contribution
