### PR TITLE
fix(sidebar): improve default size and reset default order

### LINKED ISSUE #7308: 9.0.0 reversed folder/request order
### Expected Behavior

After an update I would expect the order of my folders and request to remain the same.

### Actual Behavior

After the last update to v9.0.0 I noticed two UI issues.
1. The left column width was too wide, and it can be dragged back to make it more narrow, but to a certain size which is still to wide.
2. The order of all my folders and requests go completely inverted.The folder that used to be at the top is now at the bottom, and so on.

### Reproduction Steps

1. Accept the recent prompt to update to v9.0.0
2. After restart notice the issues

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

Version: Insomnia 9.0.0
Build date: 4/24/2024
OS: Darwin arm64 23.4.0
Electron: 29.3.0
Node: 20.9.0
Node ABI: 121
V8: 12.2.281.27-electron.0
Architecture: arm64

### Insomnia Version

9.0.0

### What operating system are you using?

macOS

### Operating System Version

14.4.1

### Installation method

So long ago that I can't remember

### Last Known Working Insomnia version

Kept up to date so whatever the previous version was

### PR DESCRIPTION
**Pull request by gatzjames**
Closes #7308

### CODE REVIEW

File: packages/insomnia/src/ui/routes/debug.tsx [hunk 1]
```diff
@@ -684,7 +684,7 @@ export const Debug: FC = () => {
 
   return (
     <PanelGroup ref={sidebarPanelRef} autoSaveId="insomnia-sidebar" id="wrapper" className='new-sidebar w-full h-full text-[--color-font]' direction='horizontal'>
-      <Panel id="sidebar" className='sidebar theme--sidebar' maxSize={40} minSize={20} collapsible>
+      <Panel id="sidebar" className='sidebar theme--sidebar' defaultSize={25} maxSize={40} minSize={20} collapsible>
```
Comment (jackkav) [inline packages/insomnia/src/ui/routes/debug.tsx:687]:
```suggestion
      <Panel id="sidebar" className='sidebar theme--sidebar' defaultSize={DEFAULT_SIDEBAR_SIZE} maxSize={40} minSize={10} collapsible>
```

Comment (jackkav) [inline packages/insomnia/src/ui/routes/debug.tsx]: use constant and reduce min size

**Review by filfreire — APPROVED** [review]

**Review by jackkav — APPROVED** [review]
