### PR TITLE
fix: #6304 git clone collections

### LINKED ISSUE #6304: Git clone existing Insomnia collection from repository fails
### Expected Behavior

Clone existing collection with "git clone" functionality

### Actual Behavior

Insomania crashes with follwoing error

image

After clicking reload app, the collection is shown as a Document:

image

Entering the document, results in the same crash

### Reproduction Steps

1. Create a collection
2. Create a request
3. Git Sync collection (commit and push)
4. Validate in git that .insomnia folder was created and collection is inside
5. Delete collection
6. Git Clone repository used before
7. Insomnia crashes

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

- There's a closed issue https://github.com/Kong/insomnia/issues/3235 which is already from 2021, don't know if it is related
- Used github integration

### Insomnia Version

2023.5.3

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Pro 22H2 22621.2134

### Installation method

insomnia.rest

### Last Known Working Insomnia version

none

### PR DESCRIPTION
**Pull request by filfreire**
changelog(Fixes): Fixed issue #6304 where cloning git synced collections wasn't working properly

Closes #6304 

When we git cloned we were hard-coding design as scope in some places. In this PR we try to fix that and also fix the route that we redirect to when we clone/re-clone.

Useful repos to use when testing this PR:

- https://github.com/filfreire/dino-park-insomnia (Design Doc)
- https://github.com/filfreire/dino-park-collection-only (Collection)

### CODE REVIEW

File: packages/insomnia/src/ui/routes/git-actions.tsx [hunk 1]
```diff
@@ -543,7 +560,12 @@ export const cloneGitRepoAction: ActionFunction = async ({
     const existingWorkspace = await models.workspace.getById(workspace._id);
 
     if (existingWorkspace) {
-      return redirect(`/organization/${existingWorkspace.parentId || DEFAULT_ORGANIZATION_ID}/project/${existingWorkspace.parentId || DEFAULT_PROJECT_ID}/workspace/${existingWorkspace._id}/debug`);
+      // if collection scope, redirect to debug instead
+      if (existingWorkspace.scope === WorkspaceScopeKeys.collection) {
+        return redirect(`/organization/${existingWorkspace.parentId || DEFAULT_ORGANIZATION_ID}/project/${existingWorkspace.parentId || DEFAULT_PROJECT_ID}/workspace/${existingWorkspace._id}/debug`);
+      }
+
+      return redirect(`/organization/${existingWorkspace.parentId || DEFAULT_ORGANIZATION_ID}/project/${existingWorkspace.parentId || DEFAULT_PROJECT_ID}/workspace/${existingWorkspace._id}/${ACTIVITY_SPEC}`);
```
Comment (jackkav) [inline packages/insomnia/src/ui/routes/git-actions.tsx]: i think its fine to redirect to debug in both cases

File: packages/insomnia/src/ui/routes/git-actions.tsx [hunk 2]
```diff
@@ -476,15 +476,32 @@ export const cloneGitRepoAction: ActionFunction = async ({
...
   };
 
+  // get workspace scope from workspace dir
+  const getWorkspaceScopeFromWorkspaceDir = async (
+    fsClient: Record<string, any>
+  ): Promise<'design' | 'collection'> => {
+    const workspaceBase = path.join(GIT_INSOMNIA_DIR, models.workspace.type);
+    const workspaces = await fsClient.promises.readdir(workspaceBase);
+    const workspacePath = path.join(workspaceBase, workspaces[0]);
+    const workspaceJson = await fsClient.promises.readFile(workspacePath);
```
Comment (jackkav) [inline packages/insomnia/src/ui/routes/git-actions.tsx]: what if there are multiple valid workspaces in this folder, this code will only get the scope for the first one and apply it to the rest.

File: packages/insomnia/src/ui/routes/git-actions.tsx [hunk 3]
```diff
@@ -476,15 +476,32 @@ export const cloneGitRepoAction: ActionFunction = async ({
...
+    if (workspace.scope === WorkspaceScopeKeys.collection) {
+      return WorkspaceScopeKeys.collection;
+    }
+    return WorkspaceScopeKeys.design;
+  };
+
   // Stop the DB from pushing updates to the UI temporarily
   const bufferId = await database.bufferChanges();
   let workspaceId = '';
+  const scope = await getWorkspaceScopeFromWorkspaceDir(fsClient);
```
Comment (jackkav) [inline packages/insomnia/src/ui/routes/git-actions.tsx]: this function should be moved to line 524 and simplified because lines 504 will never have a scope because there is no file to read.

File: packages/insomnia/src/ui/routes/git-actions.tsx (hunk 1 above)
Comment (filfreire) [reply packages/insomnia/src/ui/routes/git-actions.tsx]: fixed

File: packages/insomnia/src/ui/routes/git-actions.tsx (hunk 2 above)
Comment (filfreire) [reply packages/insomnia/src/ui/routes/git-actions.tsx]: fixed it by moving around where we check for scope

File: packages/insomnia/src/ui/routes/git-actions.tsx (hunk 3 above)
Comment (filfreire) [reply packages/insomnia/src/ui/routes/git-actions.tsx]: fixed - should be simpler now

**Review by jackkav — APPROVED** [review]
