### PR TITLE
fix: show JSON preview if content type is text/plain but body is valid json

### LINKED ISSUE #4163: text/plain responses with json are not displayed properly
### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for a bug that matches the one I want to file, without success.

### Insomnia Version

2021.6.0

### What operating system are you using?

macOS

### Operating System Version

11.6

### Installation method

dmg

### Last Known Working Insomnia version

2021.5.3

### Expected Behavior

Json with text/plain Content-Type responses to be displayed as beautified

### Actual Behavior

Response is without format

### Reproduction Steps

_No response_

### Additional Information

_No response_

### LINKED ISSUE #4168: Version 2021.6.0 breaks graphql preview
### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for a bug that matches the one I want to file, without success.

### Insomnia Version

2021.6.0

### What operating system are you using?

macOS

### Operating System Version

macOS Big Sur 11.6

### Installation method

download

### Last Known Working Insomnia version

2021.5.x

### Expected Behavior

The "Preview" should show a pretty printed view of the JSON response when Accept-Encoding is set to gzip

### Actual Behavior

The "Preview" shows the same as the "Source" view

### Reproduction Steps

Execute a graphql query with a Header of Accept-Encoding gzip.

With the response view set to "Preview" it should show a pretty printed response, but it shows the "source" view

If you uncheck the Accept-Encoding gzip Header, the preview works correctly

Unchecking the Accept-Encoding gzip Header causes the Schema refresh to fail for large schemas.

With this issue I have to keep toggling the Header to get the behavior I need.

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by dimitropoulos**
closes: https://github.com/Kong/insomnia/issues/4163
closes: https://github.com/Kong/insomnia/issues/4168
closes: INS-1133

| BEFORE | AFTER |
| - | - |
| Screenshot_20211101_161431  | Screenshot_20211101_161349 |
| Screenshot_20211101_161502 | Screenshot_20211101_161516 |

This was introduced in [`ac9303b` (#2725)](https://github.com/Kong/insomnia/pull/2725/commits/ac9303bf44756e38bc1bb87517a5d9ff57e22520).  I noticed that there was high potential for a bug in this area from the moment I looked at it, but I didn't want to scope creep so I just left a comment [`c3bfad5` (#2725)](https://github.com/Kong/insomnia/pull/2725/commits/c3bfad5a6a9d55ad95d68186a9cb6eef4d05f307#diff-528e429aed8939bdb16dc6931cf82fca3b07559c278ada0be2759eefacfd4ecaR260) with a warning that I noticed that we were playing with fire.  I gotta take responsibility for this one.  In retrospect I probably should have just fixed it once I saw it had broken behavior, perhaps just in a new PR.

Ultimately, what's going on is that there was overwriting of the prop happening [in one place](https://github.com/Kong/insomnia/pull/2725/commits/ac9303bf44756e38bc1bb87517a5d9ff57e22520#diff-528e429aed8939bdb16dc6931cf82fca3b07559c278ada0be2759eefacfd4ecaR325-R330) that wasn't happening elsewhere, and and extraction, while done correctly (the code that was extracted was character-for-character copied around the file) the mutation of `contentType` _one hundred lines (and 7 return statements!) above_ created a different behavior than what was extracted since the extraction didn't have this same fix.

You may be thinking, well, were there other places that used contentType that should have, then, had this change but didn't?  The answer is yes, there were two other places where it was out of sync, and those are fixed now as well (since, it's the same bug in play).

## Testing

As for the tests, it was quite tricky to find something that works since we don't want to assert on low-level implementation details of CodeMirror.  I'm satisfied with what we (thanks @gatzjames for the help!) came up with, but would love to improve it further if there's a way to do so!

And, in case you're wondering "why not make a function that calculates the CodeMirror mode given the original content type and the body?", the answer is, simply, because those unit tests would still pass if, in the future, we mistakenly forget to calculate the content type within the code of `ResponseViewer`.  We know this is a high danger, because it already happened in the very bug that this PR fixes.  We want to test that CodeMirror is sent the right prop.  How CodeMirror represents that mode is completely outside of the concern of `ResponseViewer`.  We just want to test that it makes the right outputs for it's own inputs.

## What this PR does not do

There's quite a lot that this area of the codebase could use in the way of refactoring.  This PR tries to avoid doing so.  This is a bug fix for a regression, and hopefully not much else.

The prior behavior was to always parse the entire body as JSON on every render unconditionally (!!!) for all responses.  That ain't good.  I know.  Although that behavior is closely tied to the kind of preview that CodeMirror shows (since, a successful parse will override the Content-Type header for the purposes of what get's sent to CodeMirror), it's not in scope to change this behavior which has existed for years (see above).

### CODE REVIEW

File: packages/insomnia-app/app/ui/components/viewers/response-viewer.tsx [hunk 1]
```diff
@@ -220,7 +261,7 @@ export class ResponseViewer extends Component<Props, State> {
 
   /** Try to detect content-types if there isn't one */
   _getMode() {
-    const { contentType } = this.props;
+    const contentType = this._getContentType();
```
Comment (develohpanda) [inline packages/insomnia-app/app/ui/components/viewers/response-viewer.tsx]: Since we're introducing a compulsory parsing of content type via `this._getContentType()`, I think we should do so in the `else` block of this method.

The previous implementation didn't try to JSON parse and detect HTML before checking for XML, but now it will. We should only invoke `_getContentType` when needed, and in this method it's not needed until the else block.

Part of me also says that the XML check should also exist within `_getContentType` but we don't have to go that far yet.

File: packages/insomnia-app/app/ui/components/viewers/response-viewer.tsx [hunk 2]
```diff
@@ -197,9 +197,50 @@ export class ResponseViewer extends Component<Props, State> {
...
+      // Nothing
+    }
+
+    return lowercasedOriginalContentType;
+  }
+
   _getBody() {
     const { bodyBuffer } = this.state;
-    const { contentType } = this.props;
+    const contentType = this._getContentType();
```
Comment (develohpanda) [inline packages/insomnia-app/app/ui/components/viewers/response-viewer.tsx]: Same as another comment in this PR, we should only invoke `_getContentType()` after the early exit immediately below

File: packages/insomnia-app/app/ui/components/viewers/response-viewer.tsx [hunk 3]
```diff
@@ -257,8 +298,7 @@ export class ResponseViewer extends Component<Props, State> {
       updateFilter,
       url,
     } = this.props;
-    // WARNING: props should never be overwritten!
-    let { contentType } = this.props;
+    const contentType = this._getContentType();
```
Comment (develohpanda) [inline packages/insomnia-app/app/ui/components/viewers/response-viewer.tsx]: Same as other comments, invoke after the early exits so we don't unnecessarily parse the response (especially if it's large, which is the purpose of one of the early exits in this method.

File: packages/insomnia-app/app/ui/components/viewers/__tests__/response-viewer.test.tsx [hunk 4]
```diff
@@ -0,0 +1,92 @@
...
+describe('<ResponseViewer />', () => {
+  beforeEach(globalBeforeEach);
+  it('should use plain text mode for a text/plain Content-Type with plain text body', async () => {
+    const codeEditor = await getResponseViewerChild({
+      contentType: 'text/plain',
+      getBody: () => Buffer.from('plain text'),
+    }, 'CodeEditor');
+
+    expect(codeEditor).toBeInTheDocument();
+    expect(codeEditor).toHaveAttribute('data-mode', 'text/plain');
```
Comment (develohpanda) [inline packages/insomnia-app/app/ui/components/viewers/__tests__/response-viewer.test.tsx]: Because we're setting a custom `data-mode` attribute on a div rather than actually checking what is sent to CodeMirror, I don't totally see the purpose of having a _React_ unit test for this.

This attribute being set or not has no effect on CodeMirror, so is misdirection/a false positive in some ways, and feels unnecessarily complex as a react test. It would make sense as a React unit test if we could mock CodeMirror and ensure it's receiving the expected prop.

The thing you're effectively testing is whether `_getContentType` returns the right value given the inputs. I would suggest extracting that as a standalone utility function, and testing input/output outside of the React context.

This isn't a blocker for the PR but just something to think about 🤔

**Review by develohpanda — CHANGES_REQUESTED** [review]

File: packages/insomnia-app/app/ui/components/viewers/response-viewer.tsx (hunk 1 above)
Comment (dimitropoulos) [reply packages/insomnia-app/app/ui/components/viewers/response-viewer.tsx]: > Since we're introducing a compulsory parsing

I know what you're getting at, but it's been compulsory all along, but by happenstance.  Hence, this bug appearing in the first place.  Now it's codified, that's all.  More on this below

> I think we should do so in the else block of this method.

I was trying to avoid doing refactors since, tbh, there's quite a performance penalty we've gotta be paying for parsing the body from a buffer to a string and then also parsing it to JSON on every render, as we have been all along.  I agree with you, and if you think it's in scope enough to ask for it, it's such a tiny, contained, and safe to do change, that I made it in 101c3f1581c8c327032f1f41c91319b8c2e33055.

> The previous implementation didn't try to JSON parse and detect HTML before checking for XML, but now it will.

This is not the case.  It parsed JSON unconditionally on [line 283](https://github.com/Kong/insomnia/blob/bdb4b4e6610f69e84a0ae7ea1296078c59bbe88e/packages/insomnia-app/app/ui/components/viewers/response-viewer.js#L283) of `_renderView` and then did the xml check on [line 395](https://github.com/Kong/insomnia/blob/bdb4b4e6610f69e84a0ae7ea1296078c59bbe88e/packages/insomnia-app/app/ui/components/viewers/response-viewer.js#L395) (later in the same function).  The bug, actually, was introduced because of the _undoing_ of it always trying to parse JSON.

> We should only invoke _getContentType when needed, and in this method it's not needed until the else block.

Again, see the [original implementation](https://github.com/Kong/insomnia/blob/bdb4b4e6610f69e84a0ae7ea1296078c59bbe88e/packages/insomnia-app/app/ui/components/viewers/response-viewer.js#L283).  This check was done blanketly.  I don't think it's in scope of this bug to change that behavior now.  This is a bugfix and I don't want to get more creative with it if we can at all avoid it.  Still, I am looking for a way to meet you in the middle without expanding scope much farther so 143e1e7bbcdd6fec82a9894fec98f6aa0b4caab5 moves it to right before the first usage to avoid unnecessary calculation.

> Part of me also says that the XML check should also exist within _getContentType but we don't have to go that far yet.

I know exactly what you mean.  I'd love to follow up and memoize the content type so we're not parsing on every render.  I've been sorta amazed that we've been doing that.  Seems like that's gotta be a performance problem? right?

For now, if at all possible, I want to just stay focused on the bugfix and avoid doing much more.

File: packages/insomnia-app/app/ui/components/viewers/response-viewer.tsx (hunk 2 above)
Comment (dimitropoulos) [reply packages/insomnia-app/app/ui/components/viewers/response-viewer.tsx]: sure, 2d445eb0119391aadab6e88116e0fbecbe9fe940 does this.

I'll mention that it's not apples-to-apples with the other case you commented on because `_getContentType` does the same `if (!buffer)` check.

File: packages/insomnia-app/app/ui/components/viewers/response-viewer.tsx (hunk 3 above)
Comment (dimitropoulos) [reply packages/insomnia-app/app/ui/components/viewers/response-viewer.tsx]: :+1: 
143e1e7bbcdd6fec82a9894fec98f6aa0b4caab5

File: packages/insomnia-app/app/ui/components/viewers/__tests__/response-viewer.test.tsx (hunk 4 above)
Comment (dimitropoulos) [reply packages/insomnia-app/app/ui/components/viewers/__tests__/response-viewer.test.tsx]: > rather than actually checking what is sent to CodeMirror

Do you know of another way to do this?  I could easily do it with `react-test-renderer` but I'm trying to avoid adding a dependency.

> It would make sense as a React unit test if we could mock CodeMirror and ensure it's receiving the expected prop.

I did (or, at least, tried quite hard to do) exactly that, but there were many many problems that I hit (and @gatzjames tried to help, as well) with CodeMirror specific things that the mock would then require.

> I would suggest extracting that as a standalone utility function, and testing input/output outside of the React context.

I also considered this, but consider this is _also_ a misdirection because it wouldn't test the thing we actually want to test which is whether CodeMirror is passed the right prop.  For example, someone could easily or accidentally change the prop that's passed to CodeMirror and that extracted unit test would still pass (even though the app would at that point be broken).

**Review by jackkav — APPROVED** [review]
Tested and approved, I'd prefer a utility function approach but happy to kick that can as this component api could really use some love outside of the scope of this ticket.

**Comment by dimitropoulos** [comment]
@gatzjames offered another idea, to use refs to accomplish the assertions we want.  I tried to do this in b60c783defc0f434b72340a7229b5c53f742a5d8.  @develohpanda please take a look.  The problem here, is that this expands the ref in a way that's incompatible with other areas of `ResponseViewer` (we'll need to create some type guards and use them before accessing the `focus` and `selectAll` methods in 4 places).  If you'd like to pursue that, please give it a look, otherwise, feel free to drop the commit and merge.  I realllly want to avoid any kind of maintenance or refactoring for this ticket and focus on the bug.  Lemme know your thoughts please.

**Comment by tonchis** [comment]
Thank you @dimitropoulos! I upgraded Insomnia to `2021.6.0` and am definitely impacted by this problem.

Happy to see it's being worked out.

```
Version: Insomnia 2021.6.0
Release date: 10/27/2021
OS: Darwin x64 20.6.0
Electron: 11.2.3
Node: 12.18.3
V8: 8.7.220.31-electron.0
Architecture: x64
node-libcurl: libcurl/7.73.0 OpenSSL/1.1.1k zlib/1.2.11 brotli/1.0.9 zstd/1.4.9 libidn2/2.1.1 libssh2/1.9.0 nghttp2/1.42.0
```

**Comment by dimitropoulos** [comment]
It's been a few days.  I am not pleased with the testing approach, no one seems to be, but another solution that doesn't expand scope hasn't been suggested.  This is a focused bugfix revert, only. Perhaps we can explore a better way to test this in the future.  Below is a patch for the commit I dropped that attempted to take a different approach.  I'm going to go forward with the approval of the state of the PR before that commit and drop it.  Here it is, in case we want to revisit later:

<details>
<summary>patch of refs approach</summary>

```patch
From b60c783defc0f434b72340a7229b5c53f742a5d8 Mon Sep 17 00:00:00 2001
From: Dimitri Mitropoulos <dimitrimitropoulos@gmail.com>
Date: Thu, 4 Nov 2021 17:15:41 -0400
Subject: [PATCH] [wip] uses refs instead of data-testid

---
 packages/insomnia-app/app/codemirror.d.ts     |  9 +++
 .../ui/components/codemirror/code-editor.tsx  |  1 -
 .../__tests__/response-viewer.test.tsx        | 59 ++++++++++++-------
 .../ui/components/viewers/response-viewer.tsx |  3 +-
 .../components/viewers/response-web-view.tsx  |  1 -
 5 files changed, 50 insertions(+), 23 deletions(-)

diff --git a/packages/insomnia-app/app/codemirror.d.ts b/packages/insomnia-app/app/codemirror.d.ts
index 7d11bd87f..ffeca1635 100644
--- a/packages/insomnia-app/app/codemirror.d.ts
+++ b/packages/insomnia-app/app/codemirror.d.ts
@@ -96,4 +96,13 @@ declare module 'codemirror' {
   }
 
   const keyNames: Record<number, string>;
+
+  interface EditorFromTextArea {
+    doc: {
+      mode: {
+        jsonMode?: boolean;
+        name: string;
+      };
+    };
+  }
 }
diff --git a/packages/insomnia-app/app/ui/components/codemirror/code-editor.tsx b/packages/insomnia-app/app/ui/components/codemirror/code-editor.tsx
index f23623384..3f8fd901f 100644
--- a/packages/insomnia-app/app/ui/components/codemirror/code-editor.tsx
+++ b/packages/insomnia-app/app/ui/components/codemirror/code-editor.tsx
@@ -1274,7 +1274,6 @@ export class UnconnectedCodeEditor extends Component<Props, State> {
         style={style}
         data-editor-type={type}
         data-mode={mode}
-        data-testid="CodeEditor"
       >
         <KeydownBinder onKeydown={this._handleKeyDown} />
         <div
diff --git a/packages/insomnia-app/app/ui/components/viewers/__tests__/response-viewer.test.tsx b/packages/insomnia-app/app/ui/components/viewers/__tests__/response-viewer.test.tsx
index 4f95ee135..1431988d9 100644
--- a/packages/insomnia-app/app/ui/components/viewers/__tests__/response-viewer.test.tsx
+++ b/packages/insomnia-app/app/ui/components/viewers/__tests__/response-viewer.test.tsx
@@ -1,5 +1,5 @@
 import { render } from '@testing-library/react';
-import React from 'react';
+import React, { createRef } from 'react';
 import configureMockStore from 'redux-mock-store';
 import thunk from 'redux-thunk';
 
@@ -7,7 +7,9 @@ import { globalBeforeEach } from '../../../../__jest__/before-each';
 import { reduxStateForTest } from '../../../../__jest__/redux-state-for-test';
 import { withReduxStore } from '../../../../__jest__/with-redux-store';
 import { RootState } from '../../../redux/modules';
+import { UnconnectedCodeEditor } from '../../codemirror/code-editor';
 import { ResponseViewer, ResponseViewerProps } from '../response-viewer';
+import { ResponseWebView } from '../response-web-view';
 
 const defaultProps: ResponseViewerProps = {
   bytes: 2,
@@ -44,49 +46,66 @@ document.createRange = () => {
 
 const middlewares = [thunk];
 const mockStore = configureMockStore<RootState>(middlewares);
-const getResponseViewerChild = async (overrideProps:  Partial<ResponseViewerProps>, selector: string) => {
+const getCodeEditorModeInfo = async (overrideProps:  Partial<ResponseViewerProps>) => {
   const store = mockStore(await reduxStateForTest());
-  const responseViewer = <ResponseViewer {...defaultProps} {...overrideProps} />;
-  const { getByTestId } = render(responseViewer, { wrapper: withReduxStore(store) });
-  return getByTestId(selector);
+  const ref = createRef<ResponseViewer>();
+  const responseViewer = <ResponseViewer ref={ref} {...defaultProps} {...overrideProps} />;
+  render(responseViewer, { wrapper: withReduxStore(store) });
+  const view  = ref.current?._selectableView;
+  if (view && 'codeMirror' in view) {
+    const { jsonMode, name } = view?.codeMirror?.doc?.mode || {};
+    return {
+      view,
+      jsonMode,
+      name,
+    };
+  }
+
+  return {
+    view,
+  };
 };
 
 describe('<ResponseViewer />', () => {
   beforeEach(globalBeforeEach);
   it('should use plain text mode for a text/plain Content-Type with plain text body', async () => {
-    const codeEditor = await getResponseViewerChild({
+    const { jsonMode, name, view } = await getCodeEditorModeInfo({
       contentType: 'text/plain',
       getBody: () => Buffer.from('plain text'),
-    }, 'CodeEditor');
+    });
 
-    expect(codeEditor).toBeInTheDocument();
-    expect(codeEditor).toHaveAttribute('data-mode', 'text/plain');
+    expect(view).toBeInstanceOf(UnconnectedCodeEditor);
+    expect(jsonMode).toEqual(undefined);
+    expect(name).toEqual('null');
   });
 
   it('should use JSON mode for a JSON Content-Type with valid JSON body', async () => {
-    const codeEditor = await getResponseViewerChild({
+    const { jsonMode, name, view } = await getCodeEditorModeInfo({
       contentType: 'application/json',
       getBody: () => Buffer.from('{"validJSON":true}'),
-    }, 'CodeEditor');
+    });
 
-    expect(codeEditor).toBeInTheDocument();
-    expect(codeEditor).toHaveAttribute('data-mode', 'application/json');
+    expect(view).toBeInstanceOf(UnconnectedCodeEditor);
+    expect(jsonMode).toEqual(true);
+    expect(name).toEqual('javascript');
   });
 
   it('should use JSON mode for text/plain Content-Type when the body is valid JSON', async () => {
-    const codeEditor = await getResponseViewerChild({
+    const { jsonMode, name, view } = await getCodeEditorModeInfo({
       contentType: 'text/plain',
       getBody: () => Buffer.from('{"validJSON":true}'),
-    }, 'CodeEditor');
-    expect(codeEditor).toBeInTheDocument();
-    expect(codeEditor).toHaveAttribute('data-mode', 'application/json');
+    });
+
+    expect(view).toBeInstanceOf(UnconnectedCodeEditor);
+    expect(jsonMode).toEqual(true);
+    expect(name).toEqual('javascript');
   });
 
   it('should use HTML mode for text/plain Content-Type that contains a doctype declaration', async () => {
-    const responseWebView = await getResponseViewerChild({
+    const { view } = await getCodeEditorModeInfo({
       contentType: 'text/plain',
       getBody: () => Buffer.from('<!DOCTYPE html><html></html>'),
-    }, 'ResponseWebView');
-    expect(responseWebView).toBeInTheDocument();
+    });
+    expect(view).toBeInstanceOf(ResponseWebView);
   });
 });
diff --git a/packages/insomnia-app/app/ui/components/viewers/response-viewer.tsx b/packages/insomnia-app/app/ui/components/viewers/response-viewer.tsx
index 76d1c5efe..c4b146781 100644
--- a/packages/insomnia-app/app/ui/components/viewers/response-viewer.tsx
+++ b/packages/insomnia-app/app/ui/components/viewers/response-viewer.tsx
@@ -54,7 +54,7 @@ interface State {
 
 @autoBindMethodsForReact(AUTOBIND_CFG)
 export class ResponseViewer extends Component<ResponseViewerProps, State> {
-  _selectableView: ResponseRawViewer | UnconnectedCodeEditor | null;
+  _selectableView: ResponseRawViewer | UnconnectedCodeEditor | ResponseWebView | null;
 
   state: State = {
     blockingBecauseTooLarge: false,
@@ -381,6 +381,7 @@ export class ResponseViewer extends Component<ResponseViewerProps, State> {
     if (previewMode === PREVIEW_MODE_FRIENDLY && contentType.includes('html')) {
       return (
         <ResponseWebView
+          ref={this._setSelectableViewRef}
           body={this._getBody()}
           contentType={contentType}
           key={disableHtmlPreviewJs ? 'no-js' : 'yes-js'}
diff --git a/packages/insomnia-app/app/ui/components/viewers/response-web-view.tsx b/packages/insomnia-app/app/ui/components/viewers/response-web-view.tsx
index 07e3f3532..616b5fe53 100644
--- a/packages/insomnia-app/app/ui/components/viewers/response-web-view.tsx
+++ b/packages/insomnia-app/app/ui/components/viewers/response-web-view.tsx
@@ -76,7 +76,6 @@ export class ResponseWebView extends PureComponent<Props> {
     const { webpreferences } = this.props;
     return (
       <webview
-        data-testid="ResponseWebView"
         ref={this.webview}
         src="about:blank"
         webpreferences={webpreferences}
-- 
2.32.0

```

</details>

File: packages/insomnia-app/app/ui/components/viewers/__tests__/response-viewer.test.tsx (hunk 4 above)
Comment (develohpanda) [reply packages/insomnia-app/app/ui/components/viewers/__tests__/response-viewer.test.tsx]: > For example, someone could easily or accidentally change the prop that's passed to CodeMirror and that extracted unit test would still pass (even though the app would at that point be broken).

Doesn't that apply to the data attribute appraoch, too? What guarantees that the mode being set on the data attribute will always be the same as what is configured in the CodeMirror options? Misdirection all 'round.

If we were to use a data attribute approach, that should be accompanied by a unit test ensuring the mode configured in CodeMirror is the same as what is on the data attribute.

---

Because our code-base abstracts CodeMirror using our `CodeEditor` component, and `ResponseViewer` _only_ interacts with `CodeEditor`, all we need to test is if `ResponseViewer` sends the correct `mode` prop to `CodeEditor`. This does go against react-testing-lib's guidelines of testing the final output rather than components, but given the complexity IMO testing at the boundary (`CodeEditor` component props) is a lesser-evil than using data attributes we can't guarantee to be the same. 

Here's an alternative approach without using a utility, but I still believe a utility is the best way forward. feel free to revert or drop the commit: 968063b716a5001c861ff8ca5cf8501c09eb9d57.

**Comment by develohpanda** [comment]
My main concern with testing `CodeMirror` directly (which is abstracted by our `CodeEditor` component) from `ResponseViewer` is that we're over complicating it (in this particular case). Please see comment here: https://github.com/Kong/insomnia/pull/4171#discussion_r744420807.

The two approaches I would suggest are:

1. mock `CodeEditor` or `CodeMirror` (968063b716a5001c861ff8ca5cf8501c09eb9d57)
2. extract utility and test outside of a React context

>  This is a focused bugfix revert, only. Perhaps we can explore a better way to test this in the future.

Yes, I agree that this is a focused bugfix, however the tests are new, and we should either figure out an agreeable approach of writing them (utility, for example), or move them into another PR for further discussion. Especially in the case of React tests involving CodeMirror, which is complex and these are the first such tests in the area.

File: packages/insomnia-app/app/ui/components/viewers/response-viewer.tsx (hunk 1 above)
Comment (develohpanda) [reply packages/insomnia-app/app/ui/components/viewers/response-viewer.tsx]: > For now, if at all possible, I want to just stay focused on the bugfix and avoid doing much more.

I totally agree with this, hence not moving the XML check. However, we need to make sure that bug fixes don't take us backwards in terms of performance and purely reviewing the changes in this changeset, I had concerns about parsing data too early, and raised them for discussion.

Thanks for making the updates. 🙌🏽

**Review by develohpanda — APPROVED** [review]
Tested and validated with https://mockbin.org/bin/48236712-b20f-4f17-a11e-cf8dcfa6c2ae 

Let me know what you decide re: tests, however functionally this works. ✅

File: packages/insomnia-app/app/ui/components/viewers/response-viewer.tsx (hunk 1 above)
Comment (dimitropoulos) [reply packages/insomnia-app/app/ui/components/viewers/response-viewer.tsx]: Ok, since you didn't resolve the conversation I want to verify: are we now on the same page that this changeset simply reintroduced something that has been in the app for years (parsing the entire body as JSON on every render)?

File: packages/insomnia-app/app/ui/components/viewers/__tests__/response-viewer.test.tsx (hunk 4 above)
Comment (dimitropoulos) [reply packages/insomnia-app/app/ui/components/viewers/__tests__/response-viewer.test.tsx]: > Doesn't that apply to the data attribute appraoch, too?

yes.  the difference is that that's such a change would, by definition, be outside the scope of the `ResponseViewer`.  I agree strongly that there's 

> all we need to test is if ResponseViewer sends the correct mode prop to CodeEditor.

Yes, exactly.  I proposed a solution for this with introducing a new library (not ideal, even though it's from react itself), but other than that there wasn't a solution that solved the problem.

UNTILLLLLLLLLL

Your commit here.  I really like it!  It's exactly what I was looking for!

> This does go against react-testing-lib's guidelines of testing the final output

Yep.  This is just somewhere where react-testing-lib's approach breaks down.  It's not a `one-solution-to-fit-each-and-every-problem`-sorta approach.  There _isn't_ any one specific final DOM output we're testing for.  It's entirely CodeMirror's responsibility.

> is a lesser-evil than using data attributes we can't guarantee to be the same

Yep.  I know the feeling.

> but I still believe a utility is the best way forward

I addressed why this will not work (of course, as always, based on my understanding of the problem) in the description of this PR (second paragraph under "Testing").  If there's something I missed, please lemme know.  Even after this PR merges, we can always revisit.

Comment (dimitropoulos) [reply packages/insomnia-app/app/ui/components/viewers/__tests__/response-viewer.test.tsx]: also I REALLY like that we got to take away that hacky code you need for CodeMirror to work in tests.  PHEW!

**Comment by dylanjwhite** [comment]
Hi @dimitropoulos, I too am impacted by this problem.
Any idea when the update for Insomnia will include this fix?
Thanks for all your work here!

**Comment by wdawson** [comment]
Hey @dylanjwhite we don't have a strict schedule for releases, but since it's been merged it will definitely be in the next one. We're still working on a few more fixes for this next release but hope to get something out in the next few weeks.
