### PR TITLE
fix: Add state and scope input UI for MCP OAuth parameter

### LINKED ISSUE #9505: MCP: allow extra properties for tool calls
Allow passing extra params to MCP tools besides those that the tool was initialized with.

**Why?**

Because VS Code (unlike other IDEs) caches the MCP tools and does not start MCP servers until they are required by an agent. Because of that, there are situations when MCP tools get updated, but VS Code still uses the old tool params for the first request. In case a param was removed, it still sends it. And I need to test this specific case, I need to handle that param for compatibility purposes.

**How does it currently work?**

I can add an additional param in the "Parameters Overview" pane, but I get an error `must NOT have additional properties` upon clicking the "Call Tool" button.

### PR DESCRIPTION
**Pull request by cwangsmv**
### Changes
- Adding `state` and `scope` parameter for MCP OAuth
- Enhance OAuth logic to support public OAuth client
- Do not block sending MCP requests when parameters are invalid

[INS-1861](https://konghq.atlassian.net/browse/INS-1861)
Closes https://github.com/Kong/insomnia/issues/9505

[INS-1861]: https://konghq.atlassian.net/browse/INS-1861?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: packages/insomnia/src/ui/components/websockets/realtime-response-pane.tsx [hunk 1]
```diff
@@ -314,7 +314,7 @@ const RealtimeActiveResponsePane: FC<RealtimeActiveResponsePaneProps & { readySt
         <TabPanel className="flex w-full flex-1 flex-col overflow-hidden" id="events">
           <PanelGroup direction="vertical" className="grid h-full w-full grid-rows-[repeat(auto-fit,minmax(0,1fr))]">
             {response.error && !isMCPAuthError ? (
-              <ResponseErrorViewer url={response.url} error={response.error} />
+              <ResponseErrorViewer url={response.url} error={response.error} isMcpResponse />
```
Comment (ZxBing0066) [inline packages/insomnia/src/ui/components/websockets/realtime-response-pane.tsx]: Why is it hard-coded to `isMcpResponse`? 🤔

File: packages/insomnia/src/ui/components/editors/auth/o-auth-2-auth.tsx [hunk 2]
```diff
@@ -291,7 +291,7 @@ const getFieldsForGrantType = (authentication: Extract<RequestAuthentication, {
 
     advanced = [responseType, scope, state, tokenPrefix, audience];
   } else if (grantType === GRANT_TYPE_MCP_AUTH_FLOW) {
-    basic = [clientId, clientSecret, readonlyRedirectUri];
+    basic = [clientId, clientSecret, readonlyRedirectUri, state, scope];
```
Comment (ZxBing0066) [inline packages/insomnia/src/ui/components/editors/auth/o-auth-2-auth.tsx]: Should we put state and scope into advanced for consistency?

File: packages/insomnia/src/main/mcp/transport-streamable-http.ts [hunk 3]
```diff
@@ -160,7 +160,9 @@ const wrappedFetch = async (
       }
     }
 
-    const resourceMetadataUrl = extractResourceMetadataUrl(response);
+    const { resourceMetadataUrl, scope: scopeFromWWWAuthenticate } = extractWWWAuthenticateParams(response);
+    // Use scope from authenticate config if available, otherwise use scope from WWW-Authenticate header
+    const scope = 'scope' in authentication && authentication.scope ? authentication.scope : scopeFromWWWAuthenticate;
```
Comment (ZxBing0066) [inline packages/insomnia/src/main/mcp/transport-streamable-http.ts]: Nit: It may be better to trim(authentication.scope) before checking. Otherwise a space may blocks the scope from the header, which is hard to realize.

File: packages/insomnia/src/main/mcp/oauth-client-provider.ts [hunk 4]
```diff
@@ -92,11 +92,15 @@ export class McpOAuthClientProvider implements OAuthClientProvider {
     }
 
     if ('clientId' in this.mcpRequest.authentication && this.mcpRequest.authentication.clientId) {
+      const { clientId, clientSecret, clientIdIssuedAt, clientSecretExpiresAt } = this.mcpRequest.authentication;
+      // https://github.com/modelcontextprotocol/typescript-sdk/blob/main/packages/client/src/client/auth.ts#L223
+      // Set client_secret to undefined if it's not set or empty string
+      const parsedClientSecret = clientSecret && clientSecret.trim().length > 0 ? clientSecret : undefined;
```
Comment (ZxBing0066) [inline packages/insomnia/src/main/mcp/oauth-client-provider.ts:99]: So, this case is that the user cleans the input, and an empty string is sent to the backend, which causes issues?

File: packages/insomnia/src/main/mcp/oauth-client-provider.ts [hunk 5]
```diff
@@ -92,11 +92,15 @@ export class McpOAuthClientProvider implements OAuthClientProvider {
     }
 
     if ('clientId' in this.mcpRequest.authentication && this.mcpRequest.authentication.clientId) {
+      const { clientId, clientSecret, clientIdIssuedAt, clientSecretExpiresAt } = this.mcpRequest.authentication;
+      // https://github.com/modelcontextprotocol/typescript-sdk/blob/main/packages/client/src/client/auth.ts#L223
```
Comment (ZxBing0066) [inline packages/insomnia/src/main/mcp/oauth-client-provider.ts]: Let's use a permalink instead of this unstable one.

**Review by ZxBing0066 — DISMISSED** [review]

File: packages/insomnia/src/ui/components/websockets/realtime-response-pane.tsx (hunk 1 above)
Comment (cwangsmv) [reply packages/insomnia/src/ui/components/websockets/realtime-response-pane.tsx]: Refine the logic:
- For none MCP Auth related error, using `isMcpResponse` to decide whether to show settings or MCP certificate modal to `Disable SSL Validation`.
- For MCP Auth error, since users can view error details when clicking the event. Adding a new `showErrorDetails` to hide error details under this situation to avoid error details to cover events table by default

File: packages/insomnia/src/main/mcp/oauth-client-provider.ts (hunk 5 above)
Comment (cwangsmv) [reply packages/insomnia/src/main/mcp/oauth-client-provider.ts]: Fixed

File: packages/insomnia/src/ui/components/editors/auth/o-auth-2-auth.tsx (hunk 2 above)
Comment (cwangsmv) [reply packages/insomnia/src/ui/components/editors/auth/o-auth-2-auth.tsx]: Good catch, moving `state` and `scope` to advanced pane

**Review by ZxBing0066 — APPROVED** [review]
