### PR TITLE
fix: Escape key in editable field closing modals

### LINKED ISSUE #2029: [Bug] [User-Experience] Pressing ESC while renaming object closes whole modal dialog
**Describe the bug**
In some cases, if one's renaming an object, and presses ESC (to discard rename), the triggered action is exiting the current modal dialog, if any is open

**To Reproduce**
1. Go to 'Manage Environments'
2. Double click on an existing environment to start renaming it
3. Press ESC key
4. The entire environment management window closes

**Expected behavior**
(4.) The environment management window is still open, and renaming is discarded

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux Mint 19
 - Installation Method: tar.gz
 - App Version 7.1.1

**Additional context**

### PR DESCRIPTION
**Pull request by baleeds**
This PR will:
- Fix an issue where pressing escape in an editable field closed the containing modal
- Fix an issue where pressing escape in an editable field would save the current value, instead of discarding

Thanks to @serpilacar for spearheading this one!

This PR is an alternative (for better or worse) to https://github.com/Kong/insomnia/pull/2030.  The primary difference is that this PR attempts to squash the event at the source.  There are potential downsides to this approach since it could affect more than just the cases I tested.  The advantage is that this change would prevent similar bugs from occurring in the future.

Closes #2029

### CODE REVIEW

File: packages/insomnia-app/app/ui/components/base/editable.js [hunk 1]
```diff
@@ -55,9 +59,15 @@ class Editable extends PureComponent {
...
     } else if (e.keyCode === 27) {
       // Pressed Escape
-      // NOTE: This blur causes a save because we save on blur
-      // TODO: Make escape blur without saving
-      this._input && this._input.blur();
+
+      // Prevent bubbling to modals and other escape listeners.
+      e.stopPropagation();
+
+      if (this._input) {
```
Comment (gschier) [inline packages/insomnia-app/app/ui/components/base/editable.js:66]: I might be missing something but don't we want to have `this._input.blur()` here still?

**Review by gschier — CHANGES_REQUESTED** [review]
Thanks so much for taking care of this! Just one comment of the removal of the `blur` logic.

File: packages/insomnia-app/app/ui/components/base/editable.js (hunk 1 above)
Comment (baleeds) [reply packages/insomnia-app/app/ui/components/base/editable.js:66]: It's possible!  I removed it because the text input is unmounted when `editing` becomes false, so in my mind the blur state is irrelevant.

What would be the reason it's needed?

Comment (gschier) [reply packages/insomnia-app/app/ui/components/base/editable.js:66]: I think the blur is there so the `onBlur` handler gets called, which actually just calls `_handleEditEnd` anyway.

I think I see why you made this change now. Currently, pressing `escape` blurs the input but still saves the value. With your change, the value will be reverted to the original. I like it!

**Review by gschier — APPROVED** [review]
Thanks for taking care of this!
