### PR TITLE
Solve the bug related to importing multiple workspaces in one file [INS-5077]

### LINKED ISSUE #8424: Import of Collections results in  Error: New Requests missing `parentId`
### Expected Behavior

The insomnia import tool ought to have imported the entire collection set without throwing any errors.

### Actual Behavior

The import fails with the message. `Error: New Requests missing 'parentId'`. Noticed that in the JSON file, the parentId for "workspace" resources types was null. Tried to replace the `"parentId": null` with `"parentId": "proj_scratchpad"` but that didn't help.

### Reproduction Steps

1. Launched Insomnia 10.3.1 on my corporate laptop having Windows 11
2. Logged into Insomnia account
3. Exported the entire collections under the sole insomnia project. There are ~20 workspaces. A ~76 MB JSON file was created
4. The laptop was reset/reimaged
5. Reinstalled Insomnia after laptop was re-imaged.
6. Launched Insomnia 10.3.1 and logged in
7. Proceeded to import the Collection

### Is there an existing issue for this?

- [x] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Which sync method do you use?

- [ ] Git sync.
- [ ] Insomnia Cloud sync.
- [x] Local only

### Additional Information

Image
Image
Image
Image
Image
Image

### Insomnia Version

10.3.1

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Enterprise 24H2, OS Build 26100.3194, Windows Feature Experience Pack 1000.26100.48.0

### Installation method

download from insomnia site

### Last Known Working Insomnia version

10.3.1

### PR DESCRIPTION
**Pull request by yaoweiprc**
Close #8424 
If the user imports a file containing more than one workspace, we create a new workspace for each workspace in the file. Then, all resources in the file are added to all newly created workspaces, regardless of whether they belong to the workspace.
That is why the 'Error: New Requests missing parentId' showed up.

Now we check whether a resource belongs to a workspace before it's added to the workspace.

### CODE REVIEW

**Review by ryan-willis — DISMISSED** [review]
the filtering/traversal code is a bit if a brain teaser, but I trust you

File: packages/insomnia/src/common/import.ts [hunk 1]
```diff
@@ -239,19 +239,69 @@ export async function importResourcesToProject({ projectId }: { projectId: strin
...
+    await Promise.all(workspaceResources
+      .map(workspace => {
+        if (workspaceResources.filter(({ _id }) => _id === '__WORKSPACE_ID__').length > 1) {
+          console.warn(`There are more than one workspace with id __WORKSPACE_ID__ in the resources, the importer is ${resourceCacheItem.importer.name}`);
+        }
+        // Here if there is only one workspace in the resources, we import all resources to it
+        let resourcesInCurrentWorkspace = resources;
+        // If there are more than one workspace in the resources, we filter in the resources that belong to the current workspace
+        if (workspaceResources.length > 1) {
+          resourcesInCurrentWorkspace = filterResourcesInWorkspace(resources, workspace);
```
Comment (CurryYangxx) [inline packages/insomnia/src/common/import.ts:260]: We can try to use a one-time traverse to find the resources belong to each workspace

**Review by filfreire — DISMISSED** [review]

File: packages/insomnia-smoke-test/tests/smoke/import.test.ts [hunk 2]
```diff
@@ -0,0 +1,14 @@
+import path from 'node:path';
+
+import { expect } from '@playwright/test';
+
+import { test } from '../../playwright/test';
+
+test('can import multiple workspaces from single file', async ({ page }) => {
+  await page.getByLabel('Import').click();
+  await page.locator('[data-test-id="import-file-input"]').setInputFiles(path.join(__dirname, '../..', 'fixtures', 'multiple-workspaces.yaml'));
```
Comment (gatzjames) [inline packages/insomnia-smoke-test/tests/smoke/import.test.ts]: Using the file api tends to create some flakiness in tests.
I'd suggest to use the loadFixture api instead and use the clipboard if possible

File: packages/insomnia/src/common/import.ts [hunk 3]
```diff
@@ -239,19 +239,69 @@ export async function importResourcesToProject({ projectId }: { projectId: strin
       continue;
     }
 
+    const workspaceResources = resources.filter(isWorkspace);;
```
Comment (gatzjames) [inline packages/insomnia/src/common/import.ts]:
```suggestion
    const workspaceResources = resources.filter(isWorkspace);
```

File: packages/insomnia/src/common/import.ts (hunk 1 above)
Comment (gatzjames) [reply packages/insomnia/src/common/import.ts:260]: As a next step I think we should handle all these edge cases using schemas for all the importers.
We can embed the validation logic into the schema and apply transformations as required.
The final result would be a workspace or series of workspaces with resources or plain resources that we need to import into a workspace.
This will drastically simplify all this logic and create a convention on importing data to the app

File: packages/insomnia/src/common/import.ts [hunk 4]
```diff
@@ -239,19 +239,69 @@ export async function importResourcesToProject({ projectId }: { projectId: strin
...
+    if (track.has(id)) {
+      return id;
+    }
+    track.add(id);
+    const parentId = idToParentIdMap.get(id);
+    if (!parentId) {
+      return id;
+    }
+    return findRootId(parentId, track);
+  }
```
Comment (gatzjames) [inline packages/insomnia/src/common/import.ts]:
```suggestion
  function findRootId(id: string, existingResourceIds: Set<string>) {
    // avoid infinite loop
    if (existingResourceIds.has(id)) {
      return id;
    }
    existingResourceIds.add(id);
    const parentId = idToParentIdMap.get(id);
    if (!parentId) {
      return id;
    }
    return findRootId(parentId, existingResourceIds);
  }
```

File: packages/insomnia/src/common/import.ts [hunk 5]
```diff
@@ -450,19 +499,24 @@ const importResourcesToNewWorkspace = async (
     const model = getModel(resource.type);
 
     if (model) {
+      const newParentId = ResourceIdMap.get(resource.parentId);
+      if (!newParentId) {
+        console.warn(`Could not find new parent id for ${resource.name} ${resource._id}`);
```
Comment (gatzjames) [inline packages/insomnia/src/common/import.ts:504]: Does this mean that this resource will not be imported?
If so what will happen if it is a resource that contains other resources e.g. requestGroup?

File: packages/insomnia-smoke-test/tests/smoke/import.test.ts (hunk 2 above)
Comment (yaoweiprc) [reply packages/insomnia-smoke-test/tests/smoke/import.test.ts]: @gatzjames Yeah I found that we use clipboard in other test cases.

File: packages/insomnia/src/common/import.ts (hunk 5 above)
Comment (yaoweiprc) [reply packages/insomnia/src/common/import.ts:504]: Since we have filtered the resources before this function 'importResourcesToNewWorkspace' is called. Only resources that belong to the new workspace are in resourceCacheItem. So each resource here is supposed to have a valid parentId. I do a double-check here because the methods we use in the following codes to insert a record to the database like 'models.grpcRequest.create', 'models.request.create' will throw errors if the parentId is undefined.

File: packages/insomnia/src/common/import.ts (hunk 1 above)
Comment (yaoweiprc) [reply packages/insomnia/src/common/import.ts:260]: @CurryYangxx Yes, but let's leave it as is for now, since performance is not an urgent concern here.

Comment (yaoweiprc) [reply packages/insomnia/src/common/import.ts:260]: @gatzjames I agree.

**Review by gatzjames — APPROVED** [review]
