### PR TITLE
fix(File Renames): Retry renames for windows EPERM issue

### LINKED ISSUE #7630: Deserialize error on deleting an environment
### Expected Behavior

I would like to be able to delete an environment.

### Actual Behavior

There is an error when I try to delete an environment.

image

### Reproduction Steps

_No response_

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

_No response_

### Insomnia Version

9.3.1

### What operating system are you using?

Windows

### Operating System Version

Windows_NT x64 10.0.19045

### Installation method

download from insomnia.rest

### Last Known Working Insomnia version

_No response_

### PR DESCRIPTION
**Pull request by gatzjames**
Attempt to fix #7630

### CODE REVIEW

File: packages/insomnia/src/sync/store/drivers/graceful-rename.ts [hunk 1]
```diff
@@ -0,0 +1,44 @@
...
+      }, backoff);
+      if (backoff < 100) {
+        backoff += 10;
+      }
+      return;
+    }
+    if (cb) {
+      cb(er);
+    }
+  });
```
Comment (jackkav) [inline packages/insomnia/src/sync/store/drivers/graceful-rename.ts]: this may not work on existing files apparently https://github.com/microsoft/vscode/issues/180695#issuecomment-1644997143

**Comment by jackkav** [comment]
I think we should consider some strategy to test or at least improve the logs so if it were to happen again this solution wasn't going to make debugging even harder. in the vscode implementation they add logs to the retries to make it clear the code is working as intended, in this edge case.
https://github.com/microsoft/vscode/pull/188899/files#diff-2bf233effbb62ea789bb7c4739d222a43ccd97ed9f1219f75bb07e9dee91c1a7R529

**Review by jackkav — APPROVED** [review]
