### PR TITLE
Prompt button to fc component

### LINKED ISSUE #4977: Convert Prompt Button component into a function component.
### Expected Behavior

Hello Insomnia,

I'll try to convert the prompt-button component into a function component.

### Actual Behavior

It's a Class component.

### Reproduction Steps

_No response_

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

_No response_

### Insomnia Version

2022.5.0-beta.2

### What operating system are you using?

macOS

### Operating System Version

macOS Monterey

### Installation method

Download from insomnia.rest

### Last Known Working Insomnia version

_No response_

### PR DESCRIPTION
**Pull request by pavkout**
This PR has the following change:

* Convert prompt-button into function component.

Closes #4977

### CODE REVIEW

File: packages/insomnia/src/ui/components/base/prompt-button.tsx [hunk 1]
```diff
@@ -1,150 +1,136 @@
...
 
-import { AUTOBIND_CFG } from '../../../common/constants';
 import { Button } from './button';
 
-type States =
-  | typeof STATE_DEFAULT
-  | typeof STATE_ASK
-  | typeof STATE_DONE
-  ;
+enum States {
```
Comment (marckong) [inline packages/insomnia/src/ui/components/base/prompt-button.tsx]: nit pick - we may prefer to use a union type instead since enum will actually include the js object translation into the bundle.

File: packages/insomnia/src/ui/components/base/prompt-button.tsx [hunk 2]
```diff
@@ -1,150 +1,136 @@
...
-    ).trim();
-    const finalDoneMessage = doneMessage || 'Done';
-    let innerMsg;
-
-    if (state === STATE_ASK && addIcon) {
-      innerMsg = (
-        <span className="warning" title="Click again to confirm">
-          <i className="fa fa-exclamation-circle" />
-          {finalConfirmMessage ? <span className="space-left">{finalConfirmMessage}</span> : ''}
+  const getChildren = useCallback(() => {
```
Comment (marckong) [inline packages/insomnia/src/ui/components/base/prompt-button.tsx]: I wonder if this was necessary. If getChildren is to return different node based on props/states, why not just creating another functional component that renders them accordingly?

**Review by gatzjames — APPROVED** [review]
🚀 Tested and it works nice!
