### PR TITLE
fix: url preview should contain auth params

### LINKED ISSUE #7235: The API Key is not added to the query parameters
### Expected Behavior

When using an API key in query parameters, the parameter must be appended to the URL.

image

### Actual Behavior

The parameter is not being added now

image

### Reproduction Steps

1. Select API Key Auth as Auth Type
2. Set Add To to Query Parameters
3. Fill Key and Value fields
4. Done - parameter was not added

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

_No response_

### Insomnia Version

8.6.1

### What operating system are you using?

Windows

### Operating System Version

Windows 11 (Windows_NT x64 10.0.22631)

### Installation method

Download from official site

### Last Known Working Insomnia version

_No response_

### PR DESCRIPTION
**Pull request by ihexxa**
Changes:
- [x] fix: url preview should contain auth params

Closes: #7235 
Ref: INS-3966

### CODE REVIEW

File: packages/insomnia/src/ui/components/rendered-query-string.tsx [hunk 1]
```diff
@@ -33,24 +33,38 @@ interface Props {
 
 const defaultPreview = '...';
 
+function getQueryParamsFromAuth(auth: RequestAuthentication | {}): RequestParameter[] {
+  if (!('type' in auth)) {
```
Comment (CurryYangxx) [inline packages/insomnia/src/ui/components/rendered-query-string.tsx]: `if (!auth.type) {}` seems easier to read

Comment (jackkav) [reply packages/insomnia/src/ui/components/rendered-query-string.tsx]: I built a helper for this `getAuthObjectOrNull` if this equals null that means auth is not set or empty object or doesn't have .type I've made a suggestion for the change but please test it to confirm. These cases are all possible because request groups can have auth objects but existing ones are uninitialised and therefore undefined. In this case it shouldn't show so perhaps you don't need it.
```suggestion
  if (getAuthObjectOrNull(auth) === null) {
```

**Review by jackkav — DISMISSED** [review]

File: packages/insomnia/src/ui/components/rendered-query-string.tsx (hunk 1 above)
Comment (ihexxa) [reply packages/insomnia/src/ui/components/rendered-query-string.tsx]: Sure, let me also test this later.

Comment (jackkav) [reply packages/insomnia/src/ui/components/rendered-query-string.tsx]: this also should preview auth fields coming from folders above

**Review by jackkav — APPROVED** [review]
