### PR TITLE
fix: unable to use unix socket with grpc - [INS-5036]

### LINKED ISSUE #8387: Unable to use unix sockets with gRPC
### Expected Behavior

I can use a path like `unix:///path/to/my/socket.sock` and it successfully connects to the socket

### Actual Behavior

A "URL not specified" error is presented.

### Reproduction Steps

1. Start a gRPC server on a unix socket
2. Create a gRPC request in Insomnia with the url pointing to the socket file
3. Try to make the request

### Is there an existing issue for this?

- [x] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Which sync method do you use?

- [ ] Git sync.
- [ ] Insomnia Cloud sync.
- [x] Local only

### Additional Information

Unix sockets seem to work fine for HTTP requests, so I presume this is a bug but if not please help me redirect 🙏 

### Insomnia Version

10.3.1

### What operating system are you using?

macOS

### Operating System Version

macOS Sequoia 15.3

### Installation method

Downloaded from the website

### Last Known Working Insomnia version

_No response_

### PR DESCRIPTION
**Pull request by CurryYangxx**
Changes:
- close #8387 

Reason:
The unix URL is different from the normal grpc URL. For example: `unix:///path/to/my/socket.sock`,  the protocol is `unix`, and the host should be the whole URL. There is no pathname in this URL.
So the `new URL()` method is not suitable for handling unix grpc request.

### CODE REVIEW

**Comment by CurryYangxx** [comment]
@ryan-willis I noticed that this seems related to this pr(https://github.com/Kong/insomnia/pull/8284). Please help to take a look if this is an appropriate approach to handling this unix situation.

**Comment by CurryYangxx** [comment]
[unix-grpc.zip](https://github.com/user-attachments/files/18961505/unix-grpc.zip)
This a js script for starting a test unix socket grpc server locally.

**Review by ryan-willis — DISMISSED** [review]

File: packages/insomnia/src/network/grpc/parse-grpc-url.ts [hunk 1]
```diff
@@ -2,6 +2,14 @@ export const parseGrpcUrl = (grpcUrl: string): { url: string; enableTls: boolean
   if (!grpcUrl) {
     return { url: '', enableTls: false, path: '' };
   }
+
+  if (grpcUrl.includes('unix:')) {
```
Comment (notjaywu) [inline packages/insomnia/src/network/grpc/parse-grpc-url.ts]: Should it use `startsWith('unix:')` instead?

**Review by yaoweiprc — APPROVED** [review]
