### PR TITLE
Fix GitLab sync

### LINKED ISSUE #2138: Cannot sync with Gitlab repository
**Describe the bug**
Cannot sync with Gitlab repository

**To Reproduce**
1. Set Gitlab [personal access token](https://gitlab.com/profile/personal_access_tokens)
  
2. Copy token
  
3. Paste to insomnia designer
  
4. Pull repository. Get Error
  
5. Get the authentication error message

  ```
  HTTPError: HTTP Error: 401 Unauthorized
      at Function.discover (/Applications/Insomnia Designer.app/Contents/Resources/app.asar/node_modules/isomorphic-git/dist/for-node/isomorphic-git/index.js:6481:13)
      at process._tickCallback (internal/process/next_tick.js:68:7)
  ```

**Expected behavior**
Can be sync with Gitlab repository

**Desktop**
 - OS: [macOS 10.15.3]
 - Installation Method: [dmg]
 - App Version [2020.1.3.3486]

**Additional context**
I think it may be that the Gitlab authentication method is different from Github. I found that insomnia designer seems to use the `info/refs` API to get repository information. When I tried to use this API to get data, I found that Github and Gitlab responded differently.

I observed through the monitoring tool that the same API responds differently on Github and Gitlab
* Github:
  ```
  Request:
  curl --request GET \
    --url 'https://github.com/superj80820/study-insomnia-designer.git/info/refs?service=git-upload-pack'

  Response:
  001e# service=git-upload-pack
  000001430f97277b0f18d5c035c082067f0913cfd0999230 HEADmulti_ack thin-pack side-band side-band-64k ofs-delta shallow deepen-since deepen-not deepen-relative no-progress include-tag multi_ack_detailed allow-tip-sha1-in-want allow-reachable-sha1-in-want no-done symref=HEAD:refs/heads/master filter agent=git/github-ge76e9aafbc97
  003f0f97277b0f18d5c035c082067f0913cfd0999230 refs/heads/master
  0000
  ```
* Gitlab:
  ```
  Request:
  curl --request GET \
    --url 'https://gitlab.com/superj80820/study-insomnia-designer.git/info/refs?service=git-upload-pack'

  Response:
  HTTP Basic: Access denied
  ```

### PR DESCRIPTION
**Pull request by develohpanda**
Prompt username for git sync - closes #2138 

image

Side changes:
- update error modal to show the stacktrace in a collapsible item, similar to [suggestion](https://gist.github.com/nijikokun/a38ff35a1977675e01cc90696f97e682)
- introduced enum for documentation, because the git sync link was incorrect.
- introduce typing for error modal show options, to aid with usability

image

### CODE REVIEW

File: packages/insomnia-app/app/common/documentation.js [hunk 1]
```diff
@@ -0,0 +1,16 @@
...
+export type DocumentationArticleType = $Keys<typeof DocumentationArticle>;
+
+const DocumentationLookup: { [DocumentationArticleType]: string } = {
+  [DocumentationArticle.base]: '/',
+  [DocumentationArticle.gitSync]: '/article/96-git-sync',
+};
+
+export function getDocumentationUrl(article: DocumentationArticleType): string {
+  return `https://support.insomnia.rest${DocumentationLookup[article] || ''}`;
+}
```
Comment (gschier) [inline packages/insomnia-app/app/common/documentation.js]: Nice 👍

File: packages/insomnia-app/app/models/git-repository.js [hunk 2]
```diff
@@ -48,11 +49,11 @@ export function migrate<T>(doc: T): T {
   return doc;
 }
 
-export function create(patch: Object = {}): Promise<GitRepository> {
+export function create(patch: $Shape<GitRepository> = {}): Promise<GitRepository> {
```
Comment (gschier) [inline packages/insomnia-app/app/models/git-repository.js:41]: Yay for `$Shape`

File: packages/insomnia-app/app/sync/git/git-vcs.js [hunk 3]
```diff
@@ -235,11 +225,7 @@ export default class GitVCS {
     return git.merge({ ...this._baseOpts, ours, theirs: theirBranch });
   }
 
-  async fetch(
-    singleBranch: boolean,
-    depth: number | null,
-    creds?: GitCredentials | null,
-  ): Promise<void> {
+  async fetch(singleBranch: boolean, depth: number | null, creds: GitCredentials): Promise<void> {
```
Comment (gschier) [inline packages/insomnia-app/app/sync/git/git-vcs.js]: Even though `null` is part of the `GitCredentials` type, I think it still makes sense to denote this arg as optional. Perhaps we should remove `null` from the type and define it explicitly where the type is used?

File: packages/insomnia-app/app/sync/git/git-vcs.js [hunk 4]
```diff
@@ -2,6 +2,7 @@
 import * as git from 'isomorphic-git';
 import { trackEvent } from '../../common/analytics';
 import { httpPlugin } from './http';
+import type { GitCredentials } from '../../models/git-repository';
```
Comment (gschier) [inline packages/insomnia-app/app/sync/git/git-vcs.js]: The app already imports and knows about this Git helper, so importing from models effectively creates a circular dependency between the git logic and the app logic. I would prefer to see either the type definition moved into here, or have it duplicated in both places.

Since the Git logic is very isolated and specific, it makes sense for it to be treated more as a standalone library and thus not need to know how or where it's being used. Perhaps we could even move it to a separate Lerna package to draw a more clear separation in the future. _Note: The analytics tracking does technically violate this already, but you can't win 'em all 🤷_

File: packages/insomnia-app/app/ui/components/modals/error-modal.js [hunk 5]
```diff
@@ -45,17 +54,22 @@ class ErrorModal extends PureComponent {
...
     return (
       <Modal ref={this._setModalRef}>
         <ModalHeader>{title || 'Uh Oh!'}</ModalHeader>
         <ModalBody className="wide pad">
           {message ? <div className="notice error">{message}</div> : null}
           {error && (
-            <pre className="pad-top-sm force-wrap selectable">
-              <code>{error.stack || error}</code>
-            </pre>
+            <details>
```
Comment (gschier) [inline packages/insomnia-app/app/ui/components/modals/error-modal.js:67]: Nice use of HTML5!

File: packages/insomnia-app/app/ui/components/modals/git-repository-settings-modal.js [hunk 6]
```diff
@@ -179,17 +181,33 @@ class GitRepositorySettingsModal extends React.PureComponent<Props, State> {
...
-              </label>
+            <div className="form-row">
+              <div className="form-control form-control--outlined">
+                <label>
+                  Username
+                  <input
+                    required
+                    type="text"
+                    name="username"
+                    placeholder="Username"
```
Comment (gschier) [inline packages/insomnia-app/app/ui/components/modals/git-repository-settings-modal.js]: Nitpick: Generally placeholder should be an example value, ideally different from the label. Perhaps `MyUser` or something generic.

**Review by gschier — CHANGES_REQUESTED** [review]
A few comments. I like the way this was implemented though 👍

File: packages/insomnia-app/app/sync/git/git-vcs.js (hunk 4 above)
Comment (develohpanda) [reply packages/insomnia-app/app/sync/git/git-vcs.js]: I'd prefer to move the type definition into this git helper, and import into models, rather than duplicate. IMO type definitions should have one source of truth.

Extracting a separate package would be nice for future too 👍

File: packages/insomnia-app/app/ui/components/help-link.js [hunk 7]
```diff
@@ -1,22 +1,23 @@
...
+    const { article } = this.props;
     return (
       <Link
         noTheme
         className="help-link theme--dialog"
-        href={getDocumentationUrl(slug)}
+        href={getDocumentationUrl(article)}
         title="Read documentation">
         <i className="fa fa-question-circle" />
       </Link>
```
Comment (develohpanda) [inline packages/insomnia-app/app/ui/components/help-link.js]: No usages of `HelpLink` so I removed the component
image

File: packages/insomnia-app/app/common/documentation.js [hunk 8]
```diff
@@ -0,0 +1,7 @@
+// @flow
+function insomniaDocs(slug: string): string {
+  return `https://support.insomnia.rest${slug}`;
+}
+
+export const docsBase = insomniaDocs('/');
+export const docsGitSync = insomniaDocs('/article/96-git-sync');
```
Comment (gschier) [inline packages/insomnia-app/app/common/documentation.js:7]: Woah, this is really nice ⚡

File: packages/insomnia-app/app/ui/components/modals/index.js [hunk 9]
```diff
@@ -21,7 +23,7 @@ export function showAlert(config) {
   return showModal(AlertModal, config);
 }
 
-export function showError(config) {
+export function showError(config: ErrorModalOptions) {
```
Comment (gschier) [inline packages/insomnia-app/app/ui/components/modals/index.js:26]: 😄

**Review by gschier — APPROVED** [review]
