### PR TITLE
fix api version error

### LINKED ISSUE #6465: Application Error: Failed to render - s.spec.info.version.startsWith is not a function
### Expected Behavior

Being able to open Insomnia and access a project or the project selection screen

### Actual Behavior

When opening Insomnia, I instantly get an Application Error "Failed to render . Please report the error to [our Github Issues](https://github.com/Kong/insomnia/issues)". 

image

I notice the TypeError Text also occurs in the left hand panel as you can see on the screenshot below: 

image

Full stack trace:

```
TypeError: s.spec.info.version.startsWith is not a function
    at children (file:///C:/Users/JonH/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/project-a967a15a.js:1:28833)
    at file:///C:/Users/JonH/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:357:9275
    at Object.useMemo (file:///C:/Users/JonH/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:116:25888)
    at h2.useMemo (file:///C:/Users/JonH/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:9:6238)
    at dl (file:///C:/Users/JonH/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:357:9182)
    at kMe (file:///C:/Users/JonH/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:357:9613)
    at MMe (file:///C:/Users/JonH/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:357:9989)
    at tu (file:///C:/Users/JonH/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:357:9737)
    at QMe (file:///C:/Users/JonH/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:357:24100)
    at jS (file:///C:/Users/JonH/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:116:19553)
    at w_ (file:///C:/Users/JonH/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:118:1575)
    at rj (file:///C:/Users/JonH/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:118:46077)
    at ej (file:///C:/Users/JonH/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:118:39819)
    at Kbe (file:///C:/Users/JonH/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:118:39745)
    at Kd (file:///C:/Users/JonH/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:118:39596)
    at Ax (file:///C:/Users/JonH/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:118:35959)
    at XB (file:///C:/Users/JonH/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:118:34906)
    at T (file:///C:/Users/JonH/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:103:1591)
    at Immediate.he [as _onImmediate] (file:///C:/Users/JonH/AppData/Local/insomnia/app-2023.5.8/resources/app.asar/index-f89f6e08.js:103:1957)
    at process.processImmediate (node:internal/timers:476:21)

```

### Reproduction Steps

1. I open the application

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

The application is now unusable because I can't access projects. 
I've also tried going to preferences and exporting the data to JSON but after selecting the export file name it just closes the window and does nothing (I guess, because it wasn't able to load the projects in the first place). 
I use Insomnia reasonably frequently, and this issue has only been occuring the last few days. Definitely with 2023.5.7 and 2023.5.8. 

### Insomnia Version

2023.5.8

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Pro

### Installation method

Download (then auto-updated)

### Last Known Working Insomnia version

2023.5.6 (not 100% sure)

### PR DESCRIPTION
**Pull request by jackkav**
Fixes #6465

changelog(Fixes): Fixed issue #6465 where a render error would be through in some cases depending on the version format of an OpenAPI spec

### CODE REVIEW

**Review by filfreire — APPROVED** [review]

File: packages/insomnia/src/ui/routes/project.tsx [hunk 1]
```diff
@@ -877,7 +877,7 @@ const ProjectRoute: FC = () => {
                         {item.workspace.name}
                       </Heading>
                       <div className="flex-1 flex flex-col gap-2 justify-end text-sm text-[--hl]">
-                        {item.spec?.info?.version && (
+                        {typeof item.spec?.info?.version === 'string' && (
```
Comment (filfreire) [inline packages/insomnia/src/ui/routes/project.tsx:880]: Wonder if the version can be a number?

Comment (jackkav) [reply packages/insomnia/src/ui/routes/project.tsx:880]: the v prefix is trivial ui sugar. Not worth adding more conditions to
