### PR TITLE
[Bug Fix 1288] "Undefined" for nested variables

### LINKED ISSUE #1288: [Bug] Variable uncovering returns "undefined" for nested variables
- Insomnia Version: 6.2.3
- Operating System: Linux Mint

## Details

https://github.com/getinsomnia/insomnia/pull/1274 introduces variable uncovering (helpful), but it seems that nested variable references returns `{undefined}:<variable>`

For example use the following environment:

````
{
  "foo": {
    "bar": "foobar"
  },
  "fu": {
    "baz": "{{ foo.bar  }}"
  },
  "foobar": "foobar2",
  "fubaz": "{{foobar}}"
}
````
- Hover over the `fu.baz` value ( `{{ foo.bar }}` ), and notice it shows `{undefined}:foobar`
- Hover over the `fubaz` value ( `{{ foobar }}` ), and notice it shows `{root}:foobar2`

Expectations:

- Hovering over the value shows `{{root}}:foobar` like a non-nested value does.

Other thoughts:
 - Should the `root` reference instead say "Base Environment" to correspond to the Base Environment?

### PR DESCRIPTION
**Pull request by Gabrz**
(Fixes #1288) Extract parent from nunjucks tag when it is a nested property nested. The parent is then used to fetch the keyContext

### CODE REVIEW

File: packages/insomnia-app/app/common/render.js [hunk 1]
```diff
@@ -237,18 +237,27 @@ export async function getRenderContext(
   const subEnvironment = await models.environment.getById(environmentId || 'n/a');
 
   let keySource = {};
-  for (let key in (rootEnvironment || {}).data) {
-    keySource[key] = 'root';
+  // Function that recursively gets keys
+  function getKeySource(subObject, inKey, inValue) {
+    for (let key in subObject) {
```
Comment (gschier) [inline packages/insomnia-app/app/common/render.js]: Please use `const key of Object.keys(subObject)` to prevent iterating over the object prototype.

File: packages/insomnia-app/app/common/render.js [hunk 2]
```diff
@@ -237,18 +237,27 @@ export async function getRenderContext(
...
+      if (typeof subObject[key] === 'string') {
+        keySource[inKey + key] = inValue;
+      } else if (typeof subObject[key] === 'object') {
```
Comment (gschier) [inline packages/insomnia-app/app/common/render.js]: Unfortunately `typeof null === 'object'` is `true` as well. Similar to `common/render.js`, these checks should use a more reliable method. https://github.com/getinsomnia/insomnia/blob/5ce2825ea94ed4a59cc6b0011776b43b292839c8/packages/insomnia-app/app/common/render.js#L158

Specifically, they should be changed to the following:

```js
typeof subObject[key] === 'string'
typeof subObject[key] === 'object'

// Should use the following, more reliable, checks instead

Object.prototype.toString.call(subObject[key]) === '[object String]'
Object.prototype.toString.call(subObject[key]) === '[object Object]'
```

File: packages/insomnia-app/app/common/render.js [hunk 3]
```diff
@@ -237,18 +237,27 @@ export async function getRenderContext(
   const subEnvironment = await models.environment.getById(environmentId || 'n/a');
 
   let keySource = {};
-  for (let key in (rootEnvironment || {}).data) {
-    keySource[key] = 'root';
+  // Function that recursively gets keys
+  function getKeySource(subObject, inKey, inValue) {
+    for (let key in subObject) {
+      if (typeof subObject[key] === 'string') {
```
Comment (gschier) [inline packages/insomnia-app/app/common/render.js]: What happens if it's a number, array, boolean, or null?

File: packages/insomnia-app/app/common/render.js [hunk 4]
```diff
@@ -237,18 +237,27 @@ export async function getRenderContext(
...
   if (subEnvironment) {
-    for (const key of Object.keys(subEnvironment.data || {})) {
-      if (subEnvironment.name) {
-        keySource[key] = subEnvironment.name;
-      }
-    }
+    getKeySource(subEnvironment.data || {}, '', subEnvironment.name || '');
   }
 
+  // Get Keys from ancestors
```
Comment (gschier) [inline packages/insomnia-app/app/common/render.js]: Nice work leaving a comment! 😄

File: packages/insomnia-app/app/common/render.js [hunk 5]
```diff
@@ -257,9 +266,7 @@ export async function getRenderContext(
         ancestor.hasOwnProperty('environment') &&
         ancestor.hasOwnProperty('name')
       ) {
-        for (const key of Object.keys(ancestor.environment || {})) {
-          keySource[key] = ancestor.name || '';
-        }
+        getKeySource(ancestor.environment || {}, '', ancestor.name || '');
```
Comment (gschier) [inline packages/insomnia-app/app/common/render.js]: Awesome. I like that this logic is grouped together in one place now.

File: packages/insomnia-app/app/common/render.js (hunk 1 above)
Comment (Gabrz) [reply packages/insomnia-app/app/common/render.js]: Thank you for your feedback! I usually don't program in JavaScript, it helped a lot that you specifically stated what you would like to have changed.

I really like Insomnia, and it would be awesome if my contribution made it into the build!
