### PR TITLE
Various k4k8s config gen bugs

### LINKED ISSUE #2102: Various Kong for Kubernetes config generation bugs
- [x] Name derived from `x-kubernetes-ingress-metadata` is not slugified
    <details>
    <summary>Example</summary>
    
    #### Source spec
    
    ```yaml
    openapi: 3.0.0
    info:
        x-kubernetes-ingress-metadata:
        name: Insomnia API
    servers:
        - url: http://api.insomnia.rest/v1
    paths:
    ```
    
    #### Current output
    
    ```yaml
    apiVersion: extensions/v1beta1
    kind: Ingress
    metadata:
        name: Insomnia API
    spec:
        rules:
        - host: api.insomnia.rest
            http:
            paths:
                - path: /v1/.*
                backend:
                    serviceName: Insomnia API-s0
                    servicePort: 80
    ```
    
    #### Expected output
    ```yaml
    apiVersion: extensions/v1beta1
    kind: Ingress
    metadata:
        name: insomnia-api
    spec:
        rules:
        - host: api.insomnia.rest
            http:
            paths:
                - path: /v1/.*
                backend:
                    serviceName: insomnia-api-s0
                    servicePort: 80
    ```
    </details>

- [x] If the server url is at root, the path rule generated is null
	<details>
	<summary>Example</summary>
	
	#### Source spec
	
	```yaml
	openapi: 3.0.0
	info:
	  title: Insomnia API
	servers:
	  - url: http://api.insomnia.rest/
	paths:
	```
	
	#### Current output
	
	```yaml
	apiVersion: extensions/v1beta1
	kind: Ingress
	metadata:
	  name: insomnia-api
	spec:
	  rules:
	    - host: api.insomnia.rest
	      http:
	        paths:
	          - path: null
	            backend:
	              serviceName: insomnia-api-s0
	              servicePort: 80
	```
	
	#### Expected output
	```yaml
	apiVersion: extensions/v1beta1
	kind: Ingress
	metadata:
	  name: insomnia-api
	spec:
	  rules:
	    - host: api.insomnia.rest
	      http:
	        paths:
	          - backend:
	              serviceName: insomnia-api-s0
	              servicePort: 80
	```
	</details>

- [x] All metadata objects on the Ingress documents for the following spec are identical; they should not be and should be as per the expected output
	<details>
	<Summary>Example</Summary>
	
	```yaml
	openapi: 3.0.0
	info:
	  x-kubernetes-ingress-metadata:
	    name: insomnia-api                          # Kubernetes Ingress document name
	    annotations:                                # Annotations to automatically apply
	      'example': 'example'
	x-kong-plugin-custom-global:                    # Global plugin to always be applied
	  name: custom-global
	  enabled: true
	  config:
	    key_in_body: false
	servers:
	  - url: http://one.insomnia.rest/v1
	  - url: http://two.insomnia.rest/v2
	    x-kong-plugin-custom-server:                # Server plugin to be applied to documents for this server
	      name: custom-server
	      enabled: true
	paths:
	  '/path':
	    post:
	      summary: Some functionality               # A path with no plugins on the path or operations in it
	  '/another-path':
	    get:
	      summary: Some functionality
	      x-kong-plugin-key-auth:                   # Operation plugin on GET /another-path
	        name: key-auth
	        enabled: true
	        config:
	          key_names: [api_key, apikey]
	          key_in_body: false
	          hide_credentials: true
	```
	</details>
	
	<details>
	<summary>Expected output</summary>

	```yaml
	apiVersion: configuration.konghq.com/v1
	kind: KongIngress
	metadata:
	  name: get-method                              # KongIngress due to GET /another-path containing a plugin
	route:
	  methods:
	    - get
	---
	apiVersion: configuration.konghq.com/v1
	kind: KongPlugin
	metadata:
	  name: add-custom-global-g0                    # KongPlugin due to plugin at OpenAPI object level
	plugin: custom-global
	config:
	  key_in_body: false
	---
	apiVersion: configuration.konghq.com/v1
	kind: KongPlugin
	metadata:
	  name: add-custom-server-s1                    # KongPlugin due to plugin on the second server
	plugin: custom-server
	---
	apiVersion: configuration.konghq.com/v1
	kind: KongPlugin
	metadata:
	  name: add-key-auth-m2                         # KongPlugin due to plugin on GET /another-path
	plugin: key-auth
	config:
	  key_names:
	    - api_key
	    - apikey
	  key_in_body: false
	  hide_credentials: true
	---
	apiVersion: extensions/v1beta1
	kind: Ingress
	metadata:
	  name: insomnia-api
	  annotations:
	    example: example                            # annotation from x-kong-ingress-metadata
	    konghq.com/plugins: add-custom-global-g0    # only global plugin
	spec:
	  rules:
	    - host: one.insomnia.rest
	      http:
	        paths:
	          - path: /v1/path
	            backend:
	              serviceName: insomnia-api-s0
	              servicePort: 80
	---
	apiVersion: extensions/v1beta1
	kind: Ingress
	metadata:
	  name: insomnia-api
	  annotations:
	    example: example
	    konghq.com/plugins: add-custom-global-g0, add-key-auth-m2   # global and operation plugin, no server or path
	    konghq.com/override: get-method             # restrict document to be for specified operation (due to plugin)
	spec:
	  rules:
	    - host: one.insomnia.rest
	      http:
	        paths:
	          - path: /v1/another
	            backend:
	              serviceName: insomnia-api-s0
	              servicePort: 80
	---
	apiVersion: extensions/v1beta1
	kind: Ingress
	metadata:
	  name: insomnia-api
	  annotations:
	    example: example
	    konghq.com/plugins: add-custom-global-g0, add-custom-server-s1    # global and server 1 plugin, no path or operation
	spec:
	  rules:
	    - host: two.insomnia.rest
	      http:
	        paths:
	          - path: /v2/path
	            backend:
	              serviceName: insomnia-api-s1
	              servicePort: 80
	---
	apiVersion: extensions/v1beta1
	kind: Ingress
	metadata:
	  name: insomnia-api
	  annotations:
	    example: example
	    konghq.com/plugins: add-custom-global-g0, add-custom-server-s1, add-key-auth-m2   # global, server 1, and operation plugin, no path
	    konghq.com/override: get-method             # restrict document to be for specified operation (due to plugin)
	spec:
	  rules:
	    - host: two.insomnia.rest
	      http:
	        paths:
	          - path: /v2/another
	            backend:
	              serviceName: insomnia-api-s1
	              servicePort: 80
	```
	</details>

### PR DESCRIPTION
**Pull request by develohpanda**
Closes #2102 - bug reports and examples in the issue.

All of the following items are fixed via TDD, with breaking tests written before fixing.

Resolves several small bugs:
- name is not sluggified
- `path: null` is invalid under an ingress document, so path should be left off
- original annotations object gets modified, resulting in all ingress documents having the same annotations

### CODE REVIEW

File: packages/openapi-2-kong/src/kubernetes/index.js [hunk 1]
```diff
@@ -226,8 +223,8 @@ export function generateServicePath(
     return undefined;
   }
 
-  const fullPath = urlJoin(serverBasePath, specificPath);
+  const fullPath = urlJoin(serverBasePath, specificPath, specificPath ? '' : '.*');
```
Comment (gschier) [inline packages/openapi-2-kong/src/kubernetes/index.js:226]: Were any tests updated to handle this `.*` suffix change?

**Review by gschier — COMMENTED** [review]
Just a small comment. Looks good otherwise!

File: packages/openapi-2-kong/src/kubernetes/index.js (hunk 1 above)
Comment (develohpanda) [reply packages/openapi-2-kong/src/kubernetes/index.js:226]: There are existing tests for this. Figured to keep the url join steps together instead of separated. No behaviour change here. https://github.com/Kong/insomnia/blob/8536da8e924b7ce9fbc907aaa2cb26ca0faf1b4b/packages/openapi-2-kong/src/kubernetes/__tests__/index.test.js#L224-L226

File: packages/openapi-2-kong/src/common.js [hunk 2]
```diff
@@ -37,14 +37,15 @@ export function getName(
...
-  }
-
-  name = name || defaultValue || 'openapi';
+  const defaultName = defaultValue || 'openapi';
+  const rawName =
+    (isKubernetes && api.info?.['x-kubernetes-ingress-metadata']?.name) ||
+    api['x-kong-name'] ||
+    api.info?.title ||
+    defaultName;
+  const name = typeof rawName === 'string' ? rawName : defaultName;
```
Comment (gschier) [inline packages/openapi-2-kong/src/common.js]: Can we break up this logic? All the ternaries, optional chaining, and `||`s make it difficult to follow.

File: packages/openapi-2-kong/src/kubernetes/index.js (hunk 1 above)
Comment (gschier) [reply packages/openapi-2-kong/src/kubernetes/index.js:226]: Oh, I see. The part I missed was on line 232 below. I didn't realize you had move the `.*` logic from there to here.

**Review by gschier — CHANGES_REQUESTED** [review]
One. Comment. Left!

**Review by gschier — APPROVED** [review]
